jupyter-book/jupyter-book

- _guide/02_setup.md
That way you still have the original page left in another tab, when you go to the linked page. 
Also, this link is not currently rendered as a link on [this page](http://predictablynoisy.com/textbooks-with-jupyter/guide/02_setup/#get-your-own-copy-of-this-repository), in my experience.
> A blank target URL here would be nice.

- scripts/generate_textbook.py
If the escaped dollar is at the beginning of the line, it does not get
replaced with the previous code, because it requires a preceding space.
This could also be done with a fancy regexp, but hey.
> Fix dollar escapes at beginning of line

- build-requirements.txt
- requirements.txt
No need for build requirements when initializing Docker containers for
notebooks.
> Split requirements into build and run

- CHANGELOG.md
- content/guide/07_advanced.md
- scripts/generate_book.py
- scripts/jupyterbook/utils.py
- scripts/tests/site/content/tests/features.md
- scripts/tests/test_build.py
This riffs off of (AKA mostly copies) @matthew-brett 's yaml splitter code so that people can put yaml frontmatter at the top of their files if they wish.
Also splits off the code into a little mini-module to make it easier to test the helper scripts
closes #51
> adding mini module and yaml splitter

- Gemfile.lock
- _includes/sidebar-toggle.html
- _layouts/default.html
- _sass/components/_components.textbook.scss
- _sass/components/_components.textbook__page.scss
- _sass/components/_components.textbook__sidebar-right.scss
- _sass/components/_components.textbook__sidebar.scss
- _sass/main.scss
> Make the sidebar stay on the page during scroll

- scripts/generate_book.py
- scripts/tests/test_build.py
- scripts/tests/test_license.py
On a case insensitive file-system, the redirect pages could write over
the originals, changing the case of file name, and breaking the links on
a static site.  This wasn't obvious serving locally on my Mac, because
the server is also working on a case-insensitive filesystem and
therefore fetches 'numbers.html' when asked for 'Numbers.html'.  But,
when built and pushed up to - say - Github - with a case-sensitive
filesystem, the breakage appears.
> Refactor textbook generator to check redirects

- _includes/js/thebelab.html
- _sass/components/_components.textbook__sidebar-right.scss
- content/guide/06_faq.md
This fixes a bug where syntax wasn't highlighted in codemirror cells w/ thebelab, also makes sure cells are not hidden if thebelab is used
> improve codemirror syntax highlighting

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/_includes/buttons.html
- jupyter_book/book_template/_includes/buttons/download.html
- jupyter_book/book_template/content/guide/04_faq.md
- jupyter_book/book_template/scripts/clean.py
- jupyter_book/build.py
This riffs off of https://github.com/jupyter/jupyter-book/pull/38 which @tomdonoghue pioneered getting a download link to work.
In that PR we were using a Zip file to download because it seemed like that was the only way to get the file to "auto" download. I found a blog post (https://www.philowen.co/blog/force-a-file-to-download-when-link-is-clicked/) that showed how to make the file automatically download even if it's an ipynb file. So, this PR does two things:
1. Adds @tomdonoghue 's commit that adds the download + zip functionality
2. Adds one more commit that strips some of this away and uses the interact link path to directly download the notebook file.
I still think that it could be a good idea to use zip files, but for now since we were only downloading the single notebook file …
> Adding download links for the notebook files

- setup.py
Addresses #105. 
This reads dependencies from the `requirements.txt` file and passes them to the `install_requires` argument in the setup.py.
> source dependencies from requirements.txt

- CONTRIBUTING.md
- README.md
Closes #99.
This is an initial commit of contributing guidelines, based largely on guidelines we use in [tedana](https://github.com/me-ica/tedana).
As a non-core developer, it'd be great to make sure this contributing process actually aligns with your expectations ! There's also some missing information here, which I'm not sure if jupyter-book yet has answers to:
Thanks ! :sparkles:
> [doc] contributing guidelines

- README.md
The current link for the markdown version of guide is not working. Hence updated the link.
> update link of the markdown version of guide

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/_includes/js/thebelab.html
This adds the codemirror theme as a configuration option - we can't merge this until thebelab cuts a new release that we can use from the CDN.
> [DNM] adding codemirror theme config

- MAINTAINING.md
This adds some simple documentation explaining the high-level site structure.
> maintaining docs for site structure

- jupyter_book/build.py
- jupyter_book/commands/__init__.py
- jupyter_book/commands/build.py
- jupyter_book/commands/create.py
- jupyter_book/commands/run.py
- jupyter_book/commands/upgrade.py
- jupyter_book/create.py
- jupyter_book/main.py
- jupyter_book/run.py
- jupyter_book/tests/test_create.py
- jupyter_book/tests/test_run.py
This PR builds on top of #126 (to avoid rebasing troubles) -- it's why the diff is large. Once that is merged into master, the diff wouldn't look so bad. It's separating the argument parsing from the actual nuts and bolts of jupyter-book. This has two advantages that I can clearly see:
- easier to debug when testing. The traceback will make more sense and it will be possible to use postmortem debugging with --pdb
- the code coverage will be correct. At the moment, it shows 0% for all the files
I just did it for build.py at the moment, but if it's useful I can do it for all the files.
> [MRG] Refactor argparse

- jupyter_book/minimal/content/features/notebooks.ipynb
The links to the raw notebook were incorrect in one of the pages of the documentation for jupyter-book. This PR fixes those links.
> Fix broken notebook links

- binder/postBuild
It seems like jupyter book is not installed in the binder build. The postBuild script should do this explicitly and fix #166
> make sure jupyter-book is included in the binder build

- jupyter_book/build.py
Adding the 'encoding' parameter to the open() function in the file handler allowed for proper book building as expected in a Windows 10 environment.
I went through the code base and found a few other file handle operations that do not declare the encoding when reading. While this is unlikely to be an issue when writing (especially since the output is formatted using the yaml library), this type of bug may be possible on the other read operations.
> [FIX] Issue #137 Errors when running on Windows

- jupyter_book/book_template/_sass/components/_components.textbook__page.scss
- jupyter_book/book_template/_sass/components/_components.textbook__sidebar-right.scss
- jupyter_book/book_template/content/features/limits.md
- jupyter_book/book_template/content/features/markdown.md
- jupyter_book/build.py
- jupyter_book/tests/site/_data/toc.yml
- jupyter_book/tests/test_create.py
These are a few miscellaneous bug fixes, mostly CSS and one build file:
* Fixes #183 (markdown guide should now be more obviously *not* a guide for this site)
* Fixes #182 (split lines wrapping for no-language code)
* Fixes #186 (external site page turn links) (there's still a UX problem of the page turns going to an external site, which is confusing, but that should be another issue)
> fixing some css bugs

- jupyter_book/book_template/content/guide/03_build.md
This PR fixes #123 by adding a couple conda-specific install steps and a mac-Mojave-specific step.
> Update local install instructions

- jupyter_book/build.py
build.py reads the kernel name from the jupyter notebooks metadata. Apparently, both the metadata and the kernelspec nodes are optional in the Jupyter notebook format, so we should make sure that they exist before we attempt to read them.
Fixes #195
> Ask if kernelspec exists in metadata

- jupyter_book/book_template/content/guide/03_build.md
Closes #220 
Changes proposed in this pull request: 
- Updates build instructions to note that full path to Jupyter Book should be provided when building with a container (Docker or Singularity)
> [DOC] Clarify full vs relative path in container build instructions

- jupyter_book/build.py
An addendum to #187 to ensure UTF-8 encoding when writing in `build_book`.  This resolves a `UnicodeDecodeError` [when building books](https://github.com/jupyter/jupyter-book/issues/137#issuecomment-501008281) in a conda 4.6.14 / Python 3.6.8 environment.
> Ensure UTF-8 Encoding When Building Book

- jupyter_book/book_template/content/features/hiding.ipynb
- jupyter_book/book_template/scripts/templates/html.tpl
- jupyter_book/build.py
- jupyter_book/run.py
- jupyter_book/utils.py
- requirements.txt
This PR does a few things:
* Removes the use of a custom template for removing inputs/outputs/etc because we discovered the nbconvert "TagRemovePreprocessor"
* Fixes up the "run a notebook" code to use the ExecutePreprocessor
* Uses the RegExpRemovePreprocessor for removing empty cells
* As a result, we no longer need `nbclean` so we're removing that dependency (which is actually pretty heavy)
* One side effect is that `stderr` will now show up in the output, though we can take that out later pretty easily
> use celltagpreprocessor to remove parts of cells and updating running code module

- jupyter_book/book_template/_includes/js/print.html
I *think* this will fix the double printing of math. The problem was that there was a second printing of math to help assistive devices, so this makes PrintJS ignore that second set of math
> fixing double math printing

- jupyter_book/book_template/content/features/markdown.md
- jupyter_book/page.py
This changes the logic for reading in text files in order to be more consistent about how markdown files are handled.
The current situation:
Any content file will be read in with jupytext. This is awesome, with the exception that some people's code **blocks** may be incorrectly parsed as code **cells** in the markdown files. In the short term, it'd be tricky to avoid that behavior from within juyptext
This PR's approach:
If a `.markdown` or `.md` file is found, read it in to memory. First see if it has any YAML header.
* If so, check if `yaml.get('jupyter').get('jupytext')` returns None.
* If so, or if there was no YAML, then assume it is a "regular" markdown file and just dump it into a single NotebookNode markdown cell. 
* If not (AKA, there's something in `yaml.jupyter.jupytext`) then …
> fixing jupytext markdown inconsistencies

- jupyter_book/book_template/_includes/js/thebelab.html
Adds an `async` attribute to the script tag to load thebelab
asynchronously. This allows the DOM to load while loading thebelab in
the background.
How I tested this:
1. Load
http://127.0.0.1:4000/jupyter-book/01/3/Plotting_the_Classics.html
2. Hard refresh the page. This results in an average DOMContentLoaded
time of 1.1s.
3. Add `async` attribute and hard refresh the page again. This results
in an average DOMContentLoaded time of 660ms, a 40% speedup.
4. To verify that this still loads thebelab, I ran a few cells on this
page using thebelab after loading asynchronously.
> Load thebelab asynchronously

- jupyter_book/book_template/_includes/js/tocbot.html
- jupyter_book/book_template/_sass/components/_components.textbook.scss
- jupyter_book/book_template/_sass/components/_components.textbook__sidebar-right.scss
This adds a tiny javascript snippet to check whether a page has any sidebar content, and if not, then the TOC will show up in narrower screens than normal. This should prevent as many cases where there is a lot of white-space to the right for unclear reasons because no sidebar content is present.
> adding right toc showing when there's no sidebar content

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/_includes/fb_tags.html
- jupyter_book/book_template/_includes/head.html
- jupyter_book/book_template/_includes/metadata.json
This commit sets a blank Jekyll excerpt as the default for all pages
([docs on excerpts][1]). Without this configuration, Jekyll tries to
generate a page excerpt using the first paragraph of each page. However,
we do not use the page excerpt anywhere in this project (since we don't
have an equivalent of a "list of all blog posts" page). Setting a blank
excerpt decreases website build time.
More importantly, in a later commit I plan to wrap HTML generated from a
Jupyter notebook in a `{% raw %}` tag ([docs][2]). Without this tag,
complicated LaTeX will break Jekyll builds. However, when Jekyll tries
to generate page excerpts, it breaks because the excerpt contains the
`{% raw %}` tag but not the `{% endraw %}` tag.
[1]: https://jekyllrb.com/docs/posts/#post-excerpts
[2]: …
> Set a blank excerpt for all pages

- jupyter_book/build.py
Because we used to wrap page title entries with quotes in YAML
front-matter, pages with a quote in the name would cause Jekyll to error
out ([like this page titled "What's in a name?"][1]).
This commit uses [YAML Block Scalars][2] to give users the greatest
flexibility when naming book sections. Section names can now contain
single quotes, double quotes, and colons.
To test this:
1. I edited `jupyter_book/book_template/_data/toc.yml`, changing the
page titled `Jupyter notebooks` to `"Sam's Cool Title: Notebooks!"`.
I verified that building the website does not break at either
`jupyter-book build` or the `jekyll build` step.
2. I opened http://127.0.0.1:4001/jupyter-book/features/notebooks.html
and verified that the sidebar had the updated title.
3. I opened …
> Don't use quotes for user-entered YAML entries

- .circleci/config.yml
This switches the CircleCI tests to use the `rb-github-pages` conda forge recipe rather than using the CircleCI Ruby docker image. This is closer to the instructions we give people in the docs, especially when #313 is merged.
> adding miniconda-based test

- jupyter_book/book_template/Makefile
- jupyter_book/book_template/content/guide/05_advanced.md
This follows up on the discussion in the GitHub issue thread for another project, [see here](https://github.com/eventmachine/eventmachine/issues/879#issuecomment-529576683).
In particular, there is now a Conda Forge package for installing GitHub Pages (and with it Jekyll, Ruby, etc.) with no need for C++ compilers or other sources of hair-pulling (at least on Mac OS X). So I also updated the Makefile to run `gem install bundler` only if Bundler is not already installed.
It took me many hours today getting all of this sorted out, so I hope these changes help others.
> Update Docs to include alternative method for building Jekyll locally.

- jupyter_book/__init__.py
- jupyter_book/book_template/_config.yml
- jupyter_book/build.py
- jupyter_book/commands/build.py
- jupyter_book/create.py
- jupyter_book/tests/configs/config_wrongversion.yml
- jupyter_book/tests/test_create.py
- jupyter_book/utils.py
This does a couple things around Jupyter Book versions and making it easier to figure out what is going wrong with a version conflict. Currently we're getting a decent number of errors because people upgrade jupyter book then run it on an older version of JB. This tries to get around that w/ the following changes:
* The version of JB is now encoded in the `_config.yml` file of the template repository (to make sure it always matches the latest JB CLI version).
* There's now a utility function that checks whether a book's version is the same as the CLI version and, if different, will instruct the person to run the upgrade command.
I'm curious if folks think it could be a problem to raise an error when there's a mismatch between the CLI and the book that it's trying to operate on. @emdupre …
> adding error message context to the build CLI command

- jupyter_book/page.py
- jupyter_book/tests/site/content/tests/notebooks.ipynb
- jupyter_book/tests/test_create.py
In LaTeX and Python it is not uncommon to have Jekyll/Liquid keywords,
like the substrings `{{` or `}}`. To tell Jekyll not to process these
as Jekyll commands, users can give cells the tag `jekyll-raw`. The
generated HTML will be wrapped in a `{% raw %}` tag.
To test this, I did the following:
1. Added a Python cell to
`./jupyter_book/book_template/content/features/notebooks.ipynb` with
the code `'{{{hello}}}'`.
2. Checked that `make book build` fails.
3. Added the `jekyll-raw` tag to the cell.
4. Checked that `make book build` succeeds, and that
http://127.0.0.1:4000/jupyter-book/features/notebooks.html has the
Python code `'{{{hello}}}'`.
> Wrap `jekyll-raw` cells with {% raw %}

- .circleci/config.yml
Removing the _build artifacts in circleci, this takes quite a long time and we rarely use it, so if we want to see the build artifacts we can probably just preview locally
> removing _build artifacts

- jupyter_book/create.py
Running jupyter-book upgrade would error if some files weren't present even if they were optional, this fixes that
> making some files optional in upgrade

- jupyter_book/build.py
this was a carryover from when we let people link to images etc that were _outside_ the content folder, but we no longer let this happen so the function isn't necessary
> removing unnecessary clean_lines function

- jupyter_book/utils.py
Closes #343.
This proposal switches version checking to a fuzzy-matching, such that only major and minor release numbers must match when building books with out-of-sync CLIs. Patch releases (as described under the semantic versioning system) are now allowed to conflict.
> fix: fuzzy matching of jupyter book versions

- setup.py
Closes https://github.com/jupyter/jupyter-book/issues/355.
- Updates required python version from 3.4 to 3.6
> Update required python version

- jupyter_book/Dockerfile
- jupyter_book/book_template/content/guide/04_publish.md
Closes #360.
- Updates the docker image to match the new image on dockerhub. 
- Updates relevant documentation describing how to use the image.
> [fix] update docker image and documentation

- jupyter_book/build.py
- jupyter_book/tests/test_create.py
This fixes a bug where interact links were placed for *all* pages, not just notebooks, because we're reading them in with jupytext now. This fixes things so they only show up for notebooks now. We might want to change that in the future but that's for another day
> fixing interact link bug

- jupyter_book/book_template/_sass/page/components/_components.page.scss
This adds an empty pseudo-element before all h2/h3/h4/h5 headers. It doesn't change the display at all but it should make it so that anchor links will snap to a vertical scroll where the headers are still visible.
For example, clicking this should center the header just under the topbar:
https://deploy-preview-366--jupyter-book.netlify.com/guide/04_publish.html#When-should-you-build-the-HTML-locally?
> adding anchors above headers

- jupyter_book/book_template/_sass/page/components/_components.page.scss
- jupyter_book/book_template/content/features/layout.ipynb
This adds a set of CSS rules for the "epigraph" tag, allowing people to add more fancy-style quotes to their pages. Here's the section that describes it:
https://5d91217509272c00083e9ba8--jupyter-book.netlify.com/features/layout.html#Quotations
Here's the new epigraph style (triggered with a tag):
and here's a slightly updated blockquote style (the default):
This was partially inspired by @stefanv and @jni 's "elegant scipy" book :-)
> adding CSS rules for epigraphs

- .circleci/config.yml
- README.md
- jupyter_book/book_template/.circleci/config.yml
- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/content/advanced/circleci.ipynb
- jupyter_book/book_template/content/advanced/netlify.md
- jupyter_book/book_template/content/features/limits.md
- jupyter_book/book_template/content/guide/02_create.md
- jupyter_book/book_template/content/guide/04_publish.md
- jupyter_book/create.py
- jupyter_book/minimal/_config.yml
- netlify.toml
- setup.py
This sets up book configuration and changes links to point to jupyterbook.org
closes #370 
we'll need to set up redirects for the `jupyter.org/jupyter-book` pages as well
> moving to jupyterbook.org

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/_includes/buttons/download.html
- jupyter_book/book_template/_includes/js/print.html
this makes the download button actually not show up if you select to do so
also adds the ability to control the header name at the top of a printed page
> fixing up download functionality

- requirements.txt
This is mostly because `jupyter_contrib_nbextensions` is a pretty big dependency
> removing unnecessary requirements

- jupyter_book/commands/page.py
- jupyter_book/page/page.py
This moves out the single-page CSS and JS bits to a function that returns the CSS/JS content. The goal is to make it easier for folks to return the CSS or JS if they want to do so without embedding it in a page's HTML.
> moving CSS and JS generation to their own function

- jupyter_book/minimal/content/intro.md
Is it "Jupyter Books" "Jupyter Book" or "Jupyter-Book"? I find this confusing.
> DOC: intro.md: Jupyter Books -> Jupyter Book

- jupyter_book/build.py
- jupyter_book/page/__init__.py
- jupyter_book/utils.py
This adds a little `ntbk` function that loads in extra yaml header information into the notebook metadata so it can be used later.
> load ntbk function

- jupyter_book/build.py
Closes #399 
Added explicit `encoding='utf8'` when opening TOC files.
> [FIX] Fixed issue with Unicode characters in TOC

- jupyter_book/build.py
- jupyter_book/page/page.py
- jupyter_book/toc.py
Closes #397 
Switched to using `os.path.split` instead of `str.split(os.sep)` when working with paths from `toc.yml`, that caused problem building on Windows.
> [FIX] Fix for path separator issue on Windows

- jupyter_book/__init__.py
- jupyter_book/book_template/scripts/clean.py
- jupyter_book/build.py
- jupyter_book/toc.py
This moves a few of the smaller modules to Pathlib, to see how the code looks and make sure that things still work properly. It significantly cleaned up the `toc.py` module, which is pretty nice :-)
> moving some modules to pathlib

- jupyter_book/tests/test_toc.py
- jupyter_book/toc.py
#403 introduced a bug in the TOC code that would keep the page extension, this fixes it and adds a test for it
> fixing toc

- jupyter_book/book_template/_includes/head.html
- jupyter_book/book_template/assets/js/page/anchors.js
- jupyter_book/book_template/assets/js/page/tocbot.js
Upgraded the vesion of `tocbot`.
Added a code to add `data-turbolinks="false"` to all `anchorjs` and `tocbot` dynamically generated links when they are generated. This should solve the issue with anchors/TOC wonky behaviour, especially when containing Unicode.
Changed `activeListItemClass` and `activeLinkClass` in `tocbot` options to be non-empty strings to fix the issue with mangled class names on generated links.
Closes #170
> [FIX] Fix for on-page anchor-based TOC issues

- jupyter_book/book_template/_includes/js/thebelab.html
This updates thebelab to use the latest released version, which should give us some extra fixes to use code highlighting
> updating thebelab and improving code highlighting

- jupyter_book/book_template/_sass/page/components/_components.page.scss
- jupyter_book/book_template/content/features/layout.ipynb
This adds CSS to handle "scrolling outputs". If the outputs are too long, then cells with this tag will have the output scrollable instead of taking up the full vertical space. This can be useful for outputs with lots of vertical space.
closes https://github.com/jupyter/jupyter-book/issues/443
apologies for taking over this one if you were planning to do it @melaniewalsh! I had an extra moment and figured I'd give it a shot
> scrolling outputs

- jupyter_book/book_template/assets/js/page/tocbot.js
This will remove the `on this page` section for pages that do not have any headers in them. It addresses some of the points in #438 from @melaniewalsh - curious what she thinks about this!
Example of no "on this page": https://deploy-preview-441--jupyter-book.netlify.com/01/what-is-data-science.html
> only show TOC if there are headers for it

- jupyter_book/book_template/_includes/js/thebelab.html
This fixes the kernel highlighting for ThebeLab. We were inferring the kernel from the parentDiv of code cells. This instead uses the `kernelName` that's defined on the page along with a helper function to make it output the right syntax for CodeMirror.
fixes #151
> fixing thebelab highlighting

- jupyter_book/book_template/_includes/js/thebelab-page-config.html
- jupyter_book/book_template/_includes/js/thebelab.html
- jupyter_book/book_template/_layouts/default.html
This moves the thebelab configuration inside `<body>` instead of `<head>` so that it is re-loaded when pages are visited with turbolinks. This should make the thebelab config properly update itself:
closes https://github.com/jupyter/jupyter-book/issues/96
> moving thebelab config to within the page instead of head

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/content/guide/05_faq.md
- jupyter_book/commands/upgrade.py
- jupyter_book/create.py
- jupyter_book/tests/configs/config_simple.yml
- jupyter_book/tests/test_create.py
This should make the upgrade functionality a little bit cleaner. Instead of copy/pasting all of the new files into the folder and storing the folder in `./mybook_NEW`, it instead uses a temporary folder and cleans out the old book folder first.
closes #434 
partially addresses https://github.com/jupyter/jupyter-book/issues/428
> improving the upgrade functionality

- .circleci/config.yml
- jupyter_book/book_template/Makefile
- jupyter_book/commands/__init__.py
- jupyter_book/commands/install.py
- jupyter_book/main.py
This adds an `install` module and CLI option, which uses Python logic to handle the installation step (currently being done with `make install`). This should let us extend this functionality if need be, and also follows the same pattern our other commands are.
> Add installation module and fix circle

- jupyter_book/book_template/content/guide/04_publish.md
book-html and github-pages are now in the `publish` sub folder
@choldgraf , what would you think of adding a _Edit on Github_ button as we see on some Sphinx documentations?
> Fix links to book-html and github-pages

- README.md
Currently the Jupyter Book icon does not appear at https://pypi.org/project/jupyter-book/ . In my experience, using the full _raw content URL_ does fix this kind of issues.
> Display the Jupyter Book icon on pypi

- jupyter_book/book_template/_data/toc.yml
- jupyter_book/book_template/content/data/gallery.yml
- jupyter_book/book_template/content/features/gallery.ipynb
This adds a small gallery of example Jupyter Books that people can look through. currently the list is manually maintained, but it's good enough for a short solution.
> adding a gallery

- jupyter_book/utils.py
This addresses #466 
Refuse to build and raise a helpful error if we encounter a page URL that doesn't begin with `os.sep` (usually `/`)
> [ENH] Raise error if page URL does not start with os.sep

- .github/workflows/tests.yml
- docs/advanced/advanced.md
- docs/customize/faq.md
- setup.py
Removes texlive install from github actions since we don't test the PDF build there.
closes https://github.com/ExecutableBookProject/jupyter-book/issues/514
> fixing tests and prep for new release

- docs/advanced/pdf.md
The current documentation [here](https://jupyterbook.org/advanced/pdf.html) tells the user to build a PDF using LaTeX through `--builder latexpdf`. The value for `--build` must instead be `pdflatex`. This PR updates the documentation to reflect this.
> update latexpdf to pdflatex in the documentation

- CONTRIBUTING.md
The current [jb contributor link](https://jupyterbook.org/contributing) is not working. This PR updates it to https://jupyterbook.org/advanced/contributing.html.
> update jb contributor link

- docs/intro.md
The `jupyter-book build` step evaluates cells in the book, which includes imports for SciPy, SymPy, and Pandas, not just NumPy and Matplotlib.
Also, a `toc` needs to be created before the build step. (There's an error message to that effect.)
Finally, once the example is built, the static images don't load—it seems they haven't been copied from `mini_book/_static` to `mini_book/docs/_build/html/_static`. This PR doesn't fix that problem, just the above two.
> Add modules needed to build the example book to the instructions.

- docs/intro.md
- docs/publish/gh-pages.md
- docs/publish/netlify.md
- docs/start/overview.md
cc @jpivarski - I believe that this will explicitly install the pre-release of only jupyter book, and not any other dependency.
closes #534 (I think that issue is being tracked in the MyST-NB repository)
> explicitly giving jupyter book install version

- docs/content/citations.md
Adding the `:all:` directive puts all references in the `.bib` file, but it doesn't actually ensure that the citations on other pages are properly captured. Instead, you have to make sure the (separate) file with the bibliography is processed last.
> Corrects info on bibliography in separate file

- docs/intro.md
I'm confused about the `environment.yaml` in the `Build the demo book` section.
There are too many demo books that I've found, so it isn't obvious what is the demo book even though one was mentioned explicitly above hehe. The instructions started with installing an environment.yaml file, and I was ended up cloning the quantecon-mini-example first and then installing that environment.yaml, then I find that in step 4 I was meant to clone the quantecon-mini-example so the environment.yaml in step 1 must have been relating to the jupyter-book repo I guess.
Should the first step be to clone the jupyter-book repo?
> Fix broken references in docs

- docs/content/myst.md
This PR updates the vscode MyST markdown extension url. The current url takes the user to a `404` error page.
> update vscode myst markdown extension url

- tests/test_clean.py
This PR addresses the failed execution of `test_clean.py` mentioned in #556. I've removed `check=True` which is throwing an error during `build --builder pdflatex`.
> add build to test_clean method prior to build  --builder pdflatex

- docs/content/execute.md
cause otherwise it won't work.
> add ticks to execute_notebooks: off in docs

- docs/advanced/pdf.md
- docs/advanced/sphinx.md
- docs/content/citations.md
- docs/content/myst.md
A few fixes to documentation from another read-through to catch up with all the exciting features. All very minor text/formatting changes, though the change in d46d7d9 warrants a closer look:
The main issue there is that a literal block (with no language specifier/info string) in [content/citations.md](https://raw.githubusercontent.com/executablebooks/jupyter-book/master/docs/content/citations.md) is using Python syntax highlighting, i.e. this:
````
```
(labels-and-refs)=
```
````
Renders [with Python syntax highlighting](https://jupyterbook.org/content/citations.html#cross-references-and-labels)
I would've expected the fenced section to have no syntax highlighting at all - in fact, this is the case for some of the fenced sections demonstrating the `{cite}` role further up in the same …
> DOC: A few documentation fix-ups

- jupyter_book/commands/__init__.py
check for the return code and return the error code when `mak all-pdf` errors
fixes https://github.com/executablebooks/jupyter-book/issues/551
This will make the build fail, when pdflatex build errors.
cc: @choldgraf @mmcky 
@choldgraf , any other requirements from that issue?
> [BUG] Added a returncode for make all-pdf

- jupyter_book/commands/__init__.py
This PR fixes a bug when `latex` config for `latex_documents` is not specified.
> FIX: fix bug when latex config not specified in project for "latex_documents"

- docs/advanced/sphinx.md
This PR adds documentation on how to add TeX macros for the whole book and specific files. It addresses comments in issue #602 and https://github.com/executablebooks/tcs_to_jb/issues/4.
> add tex macro documentation

- docs/content/myst.md
Tries to improve the documentation around using directives with MyST
I think closes #600 and #607 
what do you think about this @amueller ? If you can find other places in the text to cross-ref to this section let me know
> documenting directive keywords better

- docs/advanced/advanced.md
* Minor update in the [advanced.md](https://github.com/executablebooks/jupyter-book/blob/master/docs/advanced/advanced.md) under the `extra-navbar` section
- The author might have originally copy-pasted the content from the previous section about the 'footer' configuration, which in PR is being updated with correct info.
> Minor update for the extra-navbar section in advanced.md

- jupyter_book/pdf.py
- setup.py
In a clean environment, I see test errors in `test_pdf` due to `pyppeteer` not being installed. It's already in `setup.py` as a requirement for `pdfhtml`, but adding it to the test requirements as well prevents gets rid of the test failure.
Related to #626 but doesn't seem to be fixed there.
* Include pyppeteer in test_reqs in setup.py as it is a requirement for
test_pdf.py
* Fix package name typo in error message.
> TST: Fix test_pdf failure.

- .circleci/config.yml
This PR adds the [quantecon-mini-example](https://github.com/executablebooks/quantecon-mini-example) as a large project style build test case as part of `pdflatex` testing in `circleci`. 
The artefact is stored as `pdflatex` after each run for viewing.
When this passes testing this will supersede #635 
**Note:** This PR switches off building of `docs` as an `pdf` via circleci for now and switches over to use `quantecon-mini-example`. The `docs` pages contain mimetypes that are currently incompatible with `pdflatex` builder
> TST: [pdflatex] Add build of quantecon-mini-example as a project style test case 

- docs/_config.yml
- docs/advanced/sphinx.md
This PR adds a new latex macro retrieved from @bsamadi's example and addresses additional comments in #602. To show how it renders, I have added two commands under `_config.yml`.
@choldgraf if you would rather keep `_config.yml` clean, I can add a math directive with the new commands in `sphinx.md`. Let me know your preference.
> Additional latex newcommand example

- .circleci/config.yml
This just adjusts the test due to https://github.com/executablebooks/quantecon-mini-example/pull/26
> TST: minor update to reference book.pdf rather than python.pdf

- docs/content/citations.md
This PR adds information about how to reference `doc` and `ref` roles. It addresses #648.
The cheatsheet provides detailed information with examples. It might be beneficial to point to each relevant cheatsheet section once PR #637 is merged successfully. What do you think @choldgraf?
> How to reference docs and section labels

- .gitignore
- docs/_config.yml
- jupyter_book/__init__.py
- jupyter_book/commands/__init__.py
- jupyter_book/sphinx.py
- jupyter_book/yaml.py
This is an attempt at addressing some of the problems that @rossbar brought up earlier...
In this PR:
1. We no longer update the Sphinx configuration *within sphinx*, we instead define the Sphinx configuration in a python dictionary before calling sphinx build
2. The following precedence should take effect:
1. Hard-coded jupyter book sphinx config
2. Default Jupyter Book YAML
3. User-provided `_config.yml`
4. Over-rides from the command line
I *think* everything should behave the same, but we may run into issues with updating the configuration. I've tried to implement this in a "nested" fashion, AKA if a value is a dictionary, and it's updated with another value, then the dictionary is *updated* rather than replaced. This may or may not be appropriate in some circumstances and we should …
> improving configuration under the hood

- jupyter_book/yaml.py
ensures that a bunch of configuration values default to empty strings in case downstream stuff requires a string operation
> config defaults

- docs/start/build.md
- jupyter_book/commands/__init__.py
- tests/pages/nb_test_page_execute.ipynb
- tests/test_build.py
This is essentially a re-submission of #594 after the changes to the configuration introduced in #647 . Adds a `--execute/--no-execute` binary flag to the `page` command to control whether or not cells are to be executed when building a single page.
This replaces the existing `--execute` flag, which expects a string to specify the desired building behavior (`'off'`, `'force'`, `'cache'`, or `'auto'`). This PR also changes the default behavior so that a page is *always* executed unless the `--no-execute` flag is specified, ignoring the book-level configuration option in `_config.yml`.
Also adds tests for single-page building to `test_build.py` (which should all pass once #677 is resolved) and updates the documentation to reflect the changed behavior.
> ENH: Modify execute option for jb page command (#594 followup)

- docs/_toc.yml
- docs/reference/cheatsheet.md
This PR adds a new document containing a MyST syntax cheat sheet discussed in issue #628. 
The following content has/will been added
This PR implements one option for displaying the content. The order in which the items are displayed is not final.
Any feedback would be greatly appreciated.
> [DOC] MyST cheat sheet documentation

- docs/_config.yml
- docs/content/content-blocks.md
- docs/customize/config.md
- setup.py
This adds configuration for a "source buttons" dropdown. It replaces the "edit_this_page" button which is now part of the dropdown.
closes #664 
also closes #680 since we now pin a version of sphinx-book-theme (and other packages)
> adding configuration for source buttons

- jupyter_book/commands/__init__.py
This PR attempts to solve #659
Shortened the descriptions of CLI's clean and toc functions by rephrasing the text of their docstrings.
Signed-off-by: pgadige <poojagadige@gmail.com>
> [DOC, ENH] Shorten descriptions of clean and toc functions

- docs/advanced/advanced.md
I'm still getting a build failure with a nested _toc.yml ala #573 so I've forked [quantecon-mini-example](https://github.com/eoas-ubc/quantecon-mini-example.git) and checked in a branch with a single level toc that builds successfully.
> draft windows instructions

- docs/content/content-blocks.md
- docs/interactive/hiding.md
- jupyter_book/sphinx.py
A few documentation improvements:
* Clarifying how to use `togglebuttons` within your text
* Clarifying how to insert the output of code cells into admonitions (closes #700)
cc @najuzilu what do you think?
> misc doc improvements

- docs/content-types/myst-notebooks.md
This PR updates this [broken Jupytext link](https://jupytext.readthedocs.io/en/latest/using-server.html#paired-notebooks) with https://jupytext.readthedocs.io/en/latest/paired-notebooks.html.
> [DOC] Fix broken Jupytext link

- docs/content/content-blocks.md
Per @choldgraf's suggestion in #700 I have added some information about the `remove_cell` tag under https://jupyterbook.org/content/content-blocks.html#insert-code-cell-outputs-into-admonitions.
@choldgraf I would be happy to move the two sentences into a `note` directive if you think that's better.
> [DOC] Add info about 'remove_cell' tag

- docs/content/math.md
This PR adds a `note` directive with information that integer math labels cannot be referenced. This could be helpful to LaTeX users who are used to integer equation labels and references.
> [DOC] Add note about int eq labels in math directive

- docs/_config.yml
- docs/interactive/launchbuttons.ipynb
- docs/reference/glossary.md
* Add instructions on how to include Google Colab launch buttons 
* Include `colab_url` in the configuraiton of the docs
* Add description of Colab to Glossary and include link in docs
Note: I was not sure whether _Google Colab_ should be included in the Glossary - happy to add it if needed.
Sample output in the docs provided below.
_**Top bar:**_
_**Section:**_
Closes #716
> [DOC] Add documentation for Google Colab launch buttons

- jupyter_book/commands/__init__.py
- tests/test_build.py
Adding an `index.html` page for single-page builds, and fixing the config
> page index

- docs/interactive/launchbuttons.ipynb
This parameter is listed as `path_to_book` elsewhere on this page, and `book_path` didn't work for me while `path_to_book` did.
> Change book_path to path_to_book

- docs/contribute/develop.md
- docs/publish/gh-pages.md
- docs/start/publish.md
Simple documentation changes for the [Publish your book online](https://jupyterbook.org/start/publish.html) and [GitHub Pages and Actions](https://jupyterbook.org/publish/gh-pages.html) pages. Clarifying how to set-up a GH repo and how to use the `ghp-import` package to host with GH Pages.
Addresses #596.
> 📚 DOC: update gh-pages + ghp-import docs

- docs/customize/toc.md
- jupyter_book/toc.py
- tests/books/toc/_toc_numbered_chapters.yml
- tests/books/toc/_toc_numbered_chapters_subset.yml
- tests/test_toc.py
- tests/test_toc/_toc_numbered.html
- tests/test_toc/_toc_numbered_chapters.html
- tests/test_toc/_toc_numbered_chapters_subset.html
- tests/test_tocdirective.py
This fixes the numbering for some chapters when we have a top-level file w/ `numbered: true`
> 🐛 FIX: fixing chapters numbering

- jupyter_book/toc.py
makes sure there's enough space for the added toctrees
> 🐛 FIX: fixing toctree spacing bug

- docs/content/citations.md
This PR adds a brief note on `local bibliographies` along with links to `sphinxcontrib-bibtex` documentation. 
This is a common issue when adding multiple `bibliography` sections (ie. at the end of each lecture / page / chapter etc.) with `sphinx` throwing `duplicate citation warnings`
> 📚 DOC: note on local bibliographies for citations/references

- jupyter_book/default_config.yml
Add configuration value to launch Google Colab in the [Configuration Reference](https://jupyterbook.org/customize/config.html#configuration-reference)
closes https://github.com/executablebooks/jupyter-book/issues/788
> 📚 DOCS: Add Google Colab in the Launch Buttons

- docs/publish/gh-pages.md
- docs/publish/netlify.md
Closes #709.
Provides more detail on existing hosting solutions. Specifically:
- Specifies that if you have already built your book's HTML, we recommend GitHub pages
- Recommends Netlify over GitHub Actions, if you can't host your book on GitHub
Right now these are in-text, but I'm happy to convert them to admonitions if you think it's useful !
> 📚 DOC: Provide more documentation on hosting services

- docs/contribute/intro.md
Closes None :disappointed: 
Currently, the contributing guide has a typo that prevents it from rendering properly. This can be seen in the included screenshot, or by navigating to https://jupyterbook.org/contribute/intro.html. This PR fixes the rendering to ease interacting with the content.
> 📚 DOCS: Fix contributing guide syntax

- .pre-commit-config.yaml
- docs/_config.yml
- docs/content/content-blocks.md
- jupyter_book/commands/__init__.py
- jupyter_book/directive/toc.py
- setup.py
- tests/conftest.py
- tests/test_build.py
This adds some quick docs to show off the new `sphinx-panels` tabbed directive 👍 it also bumps our sphinx-panels version to v0.5.0
> 📚 DOCS: add sphinx-panels tabbed example

- docs/content/content-blocks.md
Adds some other cool stuff you can do with tabs, including pasting in figures etc. Addresses a question given in
https://github.com/executablebooks/meta/discussions/142
> 📚 DOCS: improving tabs docs

- jupyter_book/book_template/_config.yml
- jupyter_book/book_template/_toc.yml
In this PR I add a title and reference to the online documentation within the template files for anyone doing `jupyter-book create`. I'd like them to contain a reference to the online documentation, as it would be useful for both somewhat experienced users looking something up quickly and those that doesn't even know that the `_toc.yml` or `_config.yml` file is associated with `jupyter-book`.
> 🔧 MAINTAIN: add doc references in config/toc templates

- docs/advanced/sphinx.md
Add documentation for using justified text the book. Closes #992.
I put it as an example for modifying CSS rather than in the advanced section as suggested by @choldgraf . But I can change it if you prefer it being in the advanced section.
> 📚 DOCS: justifying text (#992)

- docs/customize/toc.md
The documentation was not reflecting that the latest change to
html.home_page_in_navbar sets the value to be true by default, rather
than false.
https://github.com/executablebooks/jupyter-book/commit/4d886b47a3889842f130ab17450530696592f407
This commit also split apart a note that were about two unrelated
points.
> 📚 DOCS: html.home_page_in_navbar defaults to true

- docs/advanced/pdf.md
- docs/advanced/sphinx.md
In https://github.com/executablebooks/sphinx-book-theme/issues/222 people asked if they could remove the table of contents when printing from HTML. This documents how users can change these kinds of things via CSS rules.
closes https://github.com/executablebooks/sphinx-book-theme/issues/222
> 📚 DOCS: instructions for custom CSS in printing HTML PDFs

- docs/advanced/pdf.md
This PR updates docs page for `pdf` files to add:
> 📚 DOCS: include configuration options available for pdflatex

- docs/file-types/myst-notebooks.md
I tried leaving off the square brackets and that syntax doesn't seem to work:
```
nbformat.validator.NotebookValidationError: 'remove-cell' is not of type 'array'
Failed validating 'type' in notebook['properties']['metadata']['properties']['tags']:
On instance['metadata']['tags']:
'remove-cell'
```
> 🔧 MAINTAIN: Fix example tag syntax

- docs/file-types/myst-notebooks.md
Also, fix examples (tag syntax, remove redundant nested `md` blocks).
Partially addresses #1040, together with #1042.
> 📚 DOCS: Clarify scope of +++ cell break feature

- docs/advanced/advanced.md
- docs/content/content-blocks.md
- docs/content/layout.md
This clarifies some of the language around markdown tagging and corrects some incorrect things in the docs
closes #1040 (or at least documents the right way to do it)
> 📚 DOCS: improving markdown tagging information

- docs/advanced/sphinx.md
Documenting how to use local Sphinx extensions within Jupyter Book.
As mentioned by @choldgraf in [this comment](https://github.com/executablebooks/jupyter-book/issues/1055#issuecomment-715926330) from #1055.
> :books: DOCS: Add local Sphinx extension documentation

- docs/intro.md
- docs/start/overview.md
In starting, I went straight from pip install into the example book, which was a lot to onboard into. The template `create` is much easier to get your head around. This PR just adds another few links to point you over to existing docs.
I realize these are above as well, but as a user I scan for what do I install and then read the lines after that. :)
> 📚  DOCS: Improve cross links on getting started

- docs/customize/toc.md
- jupyter_book/toc.py
This removes `expand_sections` from the documentation and code, as it is now deprecated in `sphinx-book-theme`
> 🗑 DEPRECATE: removing expand_sections for toc

- docs/content/figures.md
- docs/reference/cheatsheet.md
- setup.py
The upgrade to Sphinx 3.3 seems to introduce some kind of table numbering bug that is causing our docs to throw a warning (and thus error). I've got an issue open about it here:
https://github.com/sphinx-doc/sphinx/issues/8360
But can't figure out what's going on. As a precaution and to keep the tests happy, ~this pins to <3.3 until we figure out what's up. @chrisjsewell does that seem reasonable to you, or too extreme?~
EDIT: this PR now adds a title to our example tables, because @najuzilu is a badass and figured out that this was the issue. I guess technically referencing a table with a `numref` was not supposed to be possible without a title for the table.
> 📚 DOCS: adding a title to our example tables

- docs/content/code-outputs.md
- docs/content/layout.md
- docs/reference/cheatsheet.md
This PR makes some adjustment to the docs to make `output_scroll` easier to find and updates `margin` to show `tabs` for how to use it in `Jupyter Notebook` and `MyST Text File` contexts.
> 📚 DOCS: Updates to code-cell docs

- docs/_config.yml
- docs/advanced/sphinx.md
- docs/content/content-blocks.md
- docs/requirements.txt
this uses sphinx_inline_tabs instead of `sphinx-tabs` in our "extra extensions" example.
closes https://github.com/executablebooks/meta/issues/145 if @pradyunsg agrees
Example: https://deploy-preview-1099--jupyter-book.netlify.app/advanced/sphinx.html#an-example-sphinx-inline-tabs
> 📚 DOCS: sphinx_inline_tabs example

- jupyter_book/toc.py
`_gen_toctree` function was throwing variable error before we could reach this error  https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/toc.py#L149
A small check to prevent that. 
fixes https://github.com/executablebooks/jupyter-book/issues/1104
> 🐛 FIX: Check for file extensions when generating toc

- docs/advanced/sphinx.md
- docs/customize/config.md
- jupyter_book/config.py
- jupyter_book/config_schema.json
- jupyter_book/default_config.yml
- tests/test_config.py
- tests/test_config/test_get_final_config_sphinx_.yml
fixes #1055
This PR adds `local_extensions` as a component of the `sphinx` configuration to specify local extensions as `name: path` pairs. 
**Usage:**
```yaml
sphinx:
local_extensions:
helloworld: ./ext
```
`helloworld` is added to `sphinx_config['extensions']` and the `sys.path` is updated with the path variable.
> ENH: Enable local_extensions to be specified in _config.yml

- docs/publish/gh-pages.md
I'm suggesting an added step to hosting the gh-pages site. When I first tried, I didn't understand what ghp-import was doing. It's clear from the current docs that the gh-pages branch is ephemeral, but new users will find it easier to get started with clear instructions for gh-pages settings.
> 📚 DOCS: Update gh-pages.md for hosting

- docs/reference/cheatsheet.md
There are two quotation marks that appear https://jupyterbook.org/reference/cheatsheet.html#tags: `"hide-input""` should in fact be: `"hide-input"`
> 📚 DOCS: Remove extra quotation mark

- docs/file-types/markdown.md
As per the discussions with @chrisjsewell and @mmcky , removing the `align` latex environment inside a math `$$` delimiters. As it is unnecessary and buggy (breaks for latex builds)
> 📚 DOCS: Removing latex align inside math-block

- setup.py
the sphinxcontrib-bibtex extension just released 2.0 that introduced some incompatibility, so this pins to 1.0 until we can figure out how to gracefully upgrade
> 🔧 MAINT: pin sphinxcontrib-bibtex

- docs/content/myst.md
This PR fixes a broken link to `myst-parser` documentation.
> 🐛FIX: fix link to myst-parser via intersphinx

- CHANGELOG.md
- jupyter_book/__init__.py
This is a minor release to fix an issue with the release of `jupyter-book==v0.9.0` via PyPI due to a test build warning once #1129 was merged.
> 🚀 RELEASE: v0.9.1

- jupyter_book/commands/__init__.py
This fixes a bug where `.doctrees` exists, but is empty, and so our check for its existence passes but then fails when we try to take the `max` of an empty sequence. I am not sure why this bug isn't popping up in our tests, it only seems to occur under certain circumstances (maybe related to windows operating system?). But I think this will fix it.
closes #1142
> fixing mtime bug

- docs/customize/toc.md
- jupyter_book/toc.py
- tests/books/toc/_toc_numbered_depth.yml
- tests/books/toc/_toc_numbered_depth_parts_subset.yml
- tests/test_toc.py
- tests/test_toc/_toc_numbered_depth.html
- tests/test_toc/_toc_numbered_depth_parts_subset.html
Sphinx allows setting section numbering depth via the `numbered` flag, e.g., `:numbered: 3` ([see here](https://www.sphinx-doc.org/en/1.4.9/markup/toctree.html)). This PR ports such functionality to Jupyter Book, e.g.:
```yaml
- file: index
numbered: 1
chapters:
- file: content1
- file: content2
sections:
- file: content2-1
- file: content2-2
- file: content3
```
This PR should resolve executablebooks/meta#113 discussion.
> IMPROVE: set TOC numbering depth via the `numbered` flag

- docs/advanced/advanced.md
I have just discovered jupyter-book (kudos to the developers!) and I was following the documentation when I realised there was a problem with the code for setting the book's language.
The provided code:
```yaml
sphinx:
language: en
```
Does not work. (no `<html lang="en">...</html>` code is added to built book). 
If I am not wrong from https://jupyterbook.org/customize/config.html?highlight=sphinx%20config#advanced-configuration-with-sphinx , the correct code should have been:
```yaml
sphinx:
config:
language: en
```
I've tested it locally and the `<html lang="en">...</html>` is now added.
> 📚 DOCS: Fix config for setting sphinx language

- jupyter_book/default_config.yml
Hello there,
A tiny pull request to fix this orthographic typo: artifacs => artifacts
See https://en.wiktionary.org/wiki/artifact
> 🛠 MAINTAIN: Fix typo in default_config.yml

- docs/content/citations.md
`referencess.bib` should `references.bib`as far as I can tell.
> 📚 DOCS: Fix small typo

- jupyter_book/config.py
- tests/test_config/test_config_sphinx_command.txt
- tests/test_config/test_get_final_config_custom_myst_extensions.yml
- tests/test_config/test_get_final_config_empty_.yml
- tests/test_config/test_get_final_config_exclude_patterns_.yml
- tests/test_config/test_get_final_config_execute_method_.yml
- tests/test_config/test_get_final_config_extended_syntax_.yml
- tests/test_config/test_get_final_config_html_extra_footer_.yml
- tests/test_config/test_get_final_config_latex_doc_.yml
- tests/test_config/test_get_final_config_launch_buttons_.yml
- tests/test_config/test_get_final_config_repository_.yml
- tests/test_config/test_get_final_config_sphinx_.yml
- tests/test_config/test_get_final_config_title_.yml
This PR suppresses the following warning:
`WARNING: Domain 'sphinxcontrib.bibtex.domain::cite' has not implemented a `resolve_any_xref` method [myst.domains]`
The fix will be present in the next release of sphincontrib.bibtex, after which we will undo this change.
Mentioned in the following issue:
https://github.com/executablebooks/jupyter-book/issues/1228
> 🐛 FIX: Suppressing [myst.domains] warning for pdf builds

- README.md
- docs/_toc.yml
- docs/cite.md
- docs/intro.md
This adds a formal suggestion for how people can cite Jupyter Book (and I've also updated our Zenodo item).
- Updates the Zenodo DOI to point to the "generic" one for our project, so it will remain constant through new versions
- Adds a badge to `intro.md`
- Adds a `cite` page
cc @executablebooks/ebpteam in case anyone disagrees with this method of suggesting citations!
> 📚 DOCS: Add a citation page

- .github/workflows/tests.yml
This PR runs the `test.yml` through github actions on a daily basis to check for regressions introduced by the software stack. 
@chrisjsewell I am not aware of any `version` bots that could assist with this. The [renovate](https://github.com/renovatebot/renovate) app looks interesting but I haven't used it. I would be interested if anyone else has.
> TST: Run tests daily to check software stack

- setup.py
This PR upgrades `myst-nb` to `v0.12.0`
https://github.com/executablebooks/MyST-NB/blob/master/CHANGELOG.md#0120---2021-02-23
> ⬆️ UPGRADE:  myst-nb v0.12.0

- setup.py
Hi folks! I'm looking some more into the challenges of the [conda-forge PR](https://github.com/conda-forge/staged-recipes/pull/12516 )... trying another with the latest version, which lead to some more investigation.
It looks like the version pin on jupytext, which seems to move pretty fast, is starting to make it harder to get an internally consistent environment. Sigh.
This expands the pin to include the 1.10.x line, which is the first one I could get that seemed to work. We'll see what CI has to say about the matter, but no doubt there are some other insights y'all can share.
Anyhow, after some light translation of the runtime deps of HEAD (e.g. `_` to `-`, the occasional `-python`, etc.) with a `mamba` solve (one does not simple _read_ the conda errors) I'm getting:
```
Problem: …
```
> 🔧 MAINTAIN: Expand jupytext version pinning

- CHANGELOG.md
- jupyter_book/__init__.py
This PR is a minor release that updates `jupyter-book` to version `0.10.1`
[full changelog](https://github.com/executablebooks/jupyter-book/compare/v0.10.0...a73538c22d6c8c7b7b198db79ada0f801d685856)
> 🚀 RELEASE: Version 0.10.1

- jupyter_book/toc.py
Hi,
I had an issue that during toc creation with `jupyter-book toc`, files were sometimes not sorted alphanumerically. This change fixes this.
I think while `iterdir()` returns sorted entries most of the time, this is not guaranteed.
Thanks for this excellent package!
Johannes
> 🐛 FIX: Ensure sorting of files during toc creation

- jupyter_book/toc.py
FIXES: https://github.com/executablebooks/jupyter-book/issues/1049
The `_filename_to_title()` function runs `path.with_suffix("")`.
The suffix is currently stripped in  `_content_path_to_yaml()` and then again in `_filename_to_title()`. If the filename contains a `.` the second call splits the filename at the point.
Correction is: don't strip suffix in   `_content_path_to_yaml(()` .
> FIX: Error generating contents using filenames containing `.`

- setup.py
Pinning `docutils` to avoid this bug, also closes #1288 
Uses `<=` because using `~=` still results in 0.17 because a dependency installs it first.
Will push a changelog when I have a moment, going to release now if tests pass because this is a breaking bug.
> 🔧 MAINT:  pin docutils around .16

- docs/_toc.yml
- docs/advanced/index.md
- docs/advanced/pdf.md
- docs/basics/build.md
- docs/basics/building/index.md
- docs/basics/organize.md
- docs/basics/page.md
- docs/content/index.md
- docs/content/metadata.md
- docs/customize/config.md
- docs/customize/toc.md
- docs/execute/index.md
- docs/interactive/launchbuttons.ipynb
- docs/interactive/thebe.md
- docs/reference/cheatsheet.md
- docs/web/index.md
This is a continuation of #1283 to update the top level content for our docs and make them easier to browse. It nests a few things under the top header, since it's now easier for people to quickly browse those levels due to the dropdown arrow.
> 📚 DOCS: Reorganizing top-level documentation structure

- docs/reference/cheatsheet.md
There are unexpected spaces in the list-table examples of the MyST cheat sheet, causing the following error:   
`Error parsing content block for the "list-table" directive: exactly one bullet list expected.`
> 📚 DOCS: Fix indentation in list-table examples

- setup.cfg
This removes the `jupytext` dependency, because we don't use it anywhere except for in the `utils.py` module, and even there we use a try/except block to check for its install status. It looks like it was added to setup.py by myself here:
https://github.com/executablebooks/jupyter-book/commit/0ffed2688a0ee8dcefb7aeddf317b927c94981fe#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R71
but I don't think this was strictly necessary
> 🔧 MAINT: Explain jupytext dependency

- setup.cfg
This reverts a change in https://github.com/executablebooks/jupyter-book/pull/1340 that I believe was unintentional.
> ⬆ UPDATE: sphinx-external-toc v0.2.1

- setup.cfg
Neither nbconvert or nbformat are direct dependencies of jupyter-book
closes #1371
> 🔧 MAINTAIN: Remove uneeded dependencies

- docs/interactive/hiding.md
Jupyter Lab does not accept a trailing comma in arrays, for example:
```
{
"tags": [
"hide-output",
]
}
```
The PR removes these commas.
> 📚 DOCS: remove trailing comma in tags

- docs/intro.md
'twimg' causes issues with tracking, closes #1403
> 📚 DOCS: swap sloan logo to one not hosted on twitter 

- docs/basics/build.md
- jupyter_book/cli/main.py
- tests/test_build.py
This PR enables access to the `singlehtml` builder via `jupyter-book` cli
```
jb build <project> --builder=singlehtml
```
fixes #1399
> ✨IMPROVE: Enable singlehtml as a builder option from the cli

- CHANGELOG.md
- jupyter_book/__init__.py
This PR sets up `jupyter-book` for a minor release of `v0.11.3`
@choldgraf I will wait until I clarify re: `sphinx-book-theme==0.1.3` and the CHANGELOG etc.
> 🚀 RELEASE: Updates in preparation for v0.11.3 release

- docs/content/references.md
1) Most importantly, remove the **incorrect** extra tic mark in the first equation reference example.
2) Use a panel to show adding the label in the source instead of just showing the output
because how the label could be inserted was confusing without an example (although I
now see the other support ways.)
Dream wish list: Be able to use normal LaTeX \label{} in \begin{equation}, etc. ....
> DOCS: Update example of referencing equation

- docs/interactive/interactive.ipynb
Change `side`->`site`. One hopes that the widgets do not cause physical pain, although the visualizations may get under your skin 😄
> Fix typo in IPywidgets documentation

- setup.cfg
This resolves #1483 by pinning the `jsonschema` package to below the latest release (it was unpinned before). Longer term we should update the pin and fix the warning described in #1483 but this gets our tests to passing for now.
Unless there's an objection and assuming tests are happy, I'll merge this in without review (though happy to have a review if someone has the time) since the fix is simple and it un-breaks our tests on master.
> pin jsonschema

- docs/start/create.md
I just went through this nice example and suggest to add the correct filename for the **Table of Contents** here as done for the config file above too.
> docs: add (`_toc.yml`) after "Table of Contents"

- .readthedocs.yml
- docs/requirements.txt
- setup.cfg
- tests/test_build/_toc_numbered_depth_parts_subset.sphinx4.html
- tests/test_build/_toc_numbered_parts.sphinx4.html
- tests/test_build/_toc_numbered_parts_subset.sphinx4.html
- tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_parts_subset_multitoc_numbering_false.sphinx4.html
- tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_multitoc_numbering_false.sphinx4.html
- tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_subset_multitoc_numbering_false.sphinx4.html
- tests/test_tocdirective/test_toc_parts_directive.sphinx4.html
- tests/test_tocdirective/test_toc_parts_sidebar.sphinx4.html
This PR:
1. updates to `sphinx-jupyterbook-latex==0.4.6`
2. updates fixtures for `sphinx>=4.3` due to deprecation changes and adjustments in `pydata-sphinx-theme`
This update incorporates:
- Formatting of output code cells
- Adding chapter numbers in equations
- Refactored and added tests
- Added some macros in class file to better support math intensive lectures.
- Addresses missing hidden toctree attribute [PR #74](https://github.com/executablebooks/sphinx-jupyterbook-latex/pull/74)
Thanks to @Jegp and @xmnlab.
> MAINT: Upgrade to sphinx-jupyterbook-latex~=0.4.6

- CHANGELOG.md
- jupyter_book/__init__.py
This PR sets up `jupyter-book` for v0.12.1 release
> RELEASE: Setup and Changes for v0.12.1

- docs/start/overview.md
Hi, 
This is a very small change to the docs which adds back the install instructions for conda. It appears that this was previously in the documentation but then removed because it was not working: https://github.com/executablebooks/jupyter-book/pull/1034
And according to this issue, I think it was resolved: 
https://github.com/executablebooks/jupyter-book/issues/1035
The one piece that is not clear to me is if building PDFs is still an issue with jupyter-book conda (see: https://github.com/conda-forge/staged-recipes/pull/12516#discussion_r502814168). If so, maybe I should add a note?
Thanks for this great project. 
Vin
> DOC: add back conda forge in intro

- docs/customize/toc.md
This PR adds mention of singlehtml builder in the Jupyter book docs in `docs/customize/toc.md` 
under the `### Build an article from multiple files` heading. 
Not sure if this is the most appropriate place, but this is where I went when I was looking for docs on this.
Closes #1554
> [DOCS] Add mention of singlehtml builder

- docs/content/references.md
Apologies in advance for consuming review cycles for such a minor fix. I thought I misunderstood the documentation and figured I'd send the correction in case others get confused. In the doc, the section being referenced is: `Reference section labels`  but the documentation names the section as `Cross-references and labels`.
> DOC: Update header references title

- docs/sphinx/index.md
With the current version listed, I get an error "InvalidManifestError". This was fixed once I updated the version, but it took me a while to figure out what was going wrong.
> DOCS: Update pre commit jupyter book version

- docs/sphinx/index.md
I think in the old link a www is missing. At least for me only the full
https://www.sphinx-doc.org works.
> FIX: correct link to sphinx documentation

- docs/content/references.md
Clarifies some confusion that was noted in https://github.com/executablebooks/jupyter-book/issues/1119
I'll say it closes https://github.com/executablebooks/jupyter-book/issues/1119 since that issue was a bit stale, and I think this helps clarify it
> DOC: Clarify numbered references for sections

- .github/workflows/tests.yml
- setup.cfg
- tox.ini
This updates our tests + installation metadata to support pythons version 3.7/8/9
We also want to add 3.10 support, but leaving that to a follow-up PR to keep this one scoped to an easy turnaround.
ref: https://github.com/executablebooks/meta/issues/646
> MAINT: Remove Python 3.6 and add Python 3.9

- docs/structure/configure.md
This clarifies our parts numbering instructions a bit, to make it clearer how to handle multi-part numbering.
closes https://github.com/executablebooks/jupyter-book/issues/1628
> DOC: Clarify parts numbering

- docs/interactive/interactive.ipynb
This PR adds a short note to the page on interactive plotting to mention that plotly and dollarmath currently cannot be used on the same page as described in #1528.
> Add note about plotly and dollarmath incompatibility

- pyproject.toml
This pins Jinja < 3.1, so that we don't run into the bug described in:
- https://github.com/executablebooks/jupyter-book/issues/1676
closes https://github.com/executablebooks/jupyter-book/issues/1676
> PIN: Jinja < 3.1

- docs/content/references.md
The tag `<my-fig-ref>` was missing from the custom label ref example.
> fix(reference): add a missing ref

- .pre-commit-config.yaml
- CHANGELOG.md
- jupyter_book/__init__.py
This is a patch release so that people's builds aren't broken if they run into the Jinja2 pinning bug fixed in:
- #1678
> RELEASE: v0.12.3

- docs/content/code-outputs.md
- tests/test_sphinx_jupyterbook_latex/test_toc.tex
This adds a fix for [a random Sphinx error](https://github.com/executablebooks/jupyter-book/runs/6112159276?check_suite_focus=true#step:6:200) that started popping up in our docs, where it couldn't find the ColorLexer class in `myst-nb`. ~I spent 20 minutes trying to figure out how this role works and couldn't do it. So I'm hard-coding a fix and added a comment about it so we can follow up in the future.~ Ah I figured it out - the class got moved.
Will merge this quickly assuming that the tests are happy, so that we can get tests passing in all of the other open PRs as well and unblock them
> MAINT: Fix broken autodoc link and latex test

- jupyter_book/default_config.yml
I like to start a project by copying the full default `_config.yml` file and customizing from there. This PR updates the default copyright date to `"2022"`.
> MAINT: Update default config copyright date to 2022

- docs/_config.yml
- docs/advanced/sphinx.md
> FIX: fix mathjax macro syntax for sphinx>=4

- docs/content/myst.md
This PR fixes issues reported by the scheduled tests. 
However, the windows run appears to have issues resolving references due to document location:
The reported issue:
```
D:\a\jupyter-book\jupyter-book\CHANGELOG.md:22: WARNING: 'myst' reference target not found: ..\advanced\sphinx.md
```
corresponds to:
```md
- Allow recursively updating the sphinx configuration instead of totally over-writing it, see [the sphinx configuration docs](docs/advanced/sphinx.md) for details [#1599](https://github.com/executablebooks/jupyter-book/pull/1599) ([@kmpaul](https://github.com/kmpaul))
```
which looks like `sphinx` is removing `docs` and replacing it with a `..` on `windows` only. 
The directive:
````
```{include} ../../CHANGELOG.md
:relative-docs: docs/
:relative-images:
```
````
These options to …
>  MAINT: Fix reported issues from scheduled osx, and windows tests

- docs/intro.md
Front page links weren't listed as `doc` types.
closes #1741
> DOC: Fix front page links

- jupyter_book/config.py
- tests/test_config/test_config_sphinx_command.txt
- tests/test_config/test_config_sphinx_command_only_build_toc_files.txt
- tests/test_config/test_get_final_config_custom_myst_extensions.yml
- tests/test_config/test_get_final_config_empty_.yml
- tests/test_config/test_get_final_config_exclude_patterns_.yml
- tests/test_config/test_get_final_config_execute_method_.yml
- tests/test_config/test_get_final_config_extended_syntax_.yml
- tests/test_config/test_get_final_config_html_extra_footer_.yml
- tests/test_config/test_get_final_config_latex_doc_.yml
- tests/test_config/test_get_final_config_launch_buttons_.yml
- tests/test_config/test_get_final_config_repository_.yml
- tests/test_config/test_get_final_config_sphinx_default_.yml
- tests/test_config/test_get_final_config_sphinx_recurse_.yml
- tests/test_config/test_get_final_config_title_.yml
- tests/test_config/test_mathjax_config_warning.sphinx4.yml
- tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx4.yml
For Sphinx 5 compatibility.
See [release notes](https://www.sphinx-doc.org/en/master/changes.html#id15) and https://github.com/sphinx-doc/sphinx/issues/10474.
Related #1749 and https://github.com/executablebooks/meta/issues/750
----------
I know that the CI pipeline isn't running with Sphinx 5 yet, but I tested this locally by forcing a `pip install "sphinx==5.0.1"` and making this one-line change in the `jupyter-book` source.
With that my dissertation project built successfully.
> MAINT: Don't set the default language

- docs/intro.md
I think this title block should be YAML:
https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html?highlight=front#front-matter
Haven't tested if this would actually add a title though?
If this is not a typo, curious what it does!
> 📖  DOCS: Use YAML in front-matter

- docs/content/citations.md
closes  #1137 resolves path to bib file, no need to pin version of sphinxcontrib-bibtex
> DOCS: Fix missing reference to bib

- jupyter_book/sphinx.py
Setting the html_assets_policy flag  to always includes mathjax in singlehtml builder. This also helps in maths rendering for pdfhtml builder. This flag is defaulted to per_page inside sphinx codebase, which leads to excluding mathjax for singlehtml builder.
Resolves #1705
> FIX: Enable maths in singlehtml mode

- docs/content/components.md
To stay coherent with other examples written in markdown.
> DOCS: Replace ::: by ``` in admonition example

- docs/advanced/pdf.md
remove `texlive-latex-recommended` & `texlive-fonts-recommended` from `Installation and Setup` because has no effect and book builded
> DOCS: remove *-recommended libs for latex

- docs/advanced/html.md
Hello,
I wanted to add a section in the documentation about enabling and adding Plausible.io since I've now got its working.
Let me know if you'd suggest any changes to what I've written. (h/t to [@RobertJoonas](https://github.com/plausible/analytics/discussions/2117#discussioncomment-3420303) for the code and the idea).
Fixes and closes #1811.
> DOCS: Add documentation on enabling Plausible Analytics

- docs/content/metadata.md
Looks like this was left inadvertently.
> DOCS: Remove incomplete documentation section on adding metadata

- docs/publish/gh-pages.md
This is a proposal to adds instructions for configuring GitHub Pages to correctly find and deploy the built files. It is not fully obvious what happens to the built files and how that should be reflected in the settings, so I think it's worth mentioning this somewhere on this page.
If you agree it's worth adding, please let me know how it can be more clear and I'll update ASAP.
> DOC: Add guidance for configuring gh-pages

- docs/advanced/html.md
- More direct injection of plausible.io analytics, using nothing but
a standard Sphinx option.
- I have tested this in the jupyter-book docs.  This solution uses `<script
defer="defer" ...>` instead of `<script defer ...>`, but the
plausible people say it should be the same.  The advantage here is
that the configuration is more simple and stardard.
- Apparently this will also be possible by the pydata sphinx theme,
it's up to you all if you prefer theme-based or standard config
based.  Feel free to close this PR if you would rather sphinx-based.
> DOCS: document an easier method of plausible analytics

- .github/workflows/publish.yml
- .github/workflows/tests.yml
Currently we have a workflow embedded in `tests.yml` that is called only if a new release is made. However this shows us as "not run" in our test suite in github and messes with the passing tests condition.
This PR factors that out into a dedicated workflow file that is run on `publish` and _calls_ our test suite before running the publish command. That should mean the "Publish to PyPI" action never gets run unless we are publishing.
> MAINT: Move pypi publish to dedicated workflow

- docs/_config.yml
This adds the sphinx copybutton prefix configuration so that console code snippets with a leading `$` won't include the `$` in the copied text.
- closes https://github.com/executablebooks/jupyter-book/pull/1860 by superceding it
This also sorts our `config` section to be alphabetical
> DOCS: Add copybutton console prefix

- jupyter_book/book_template/markdown-notebooks.md
Before this merge, `jupyter-book create mynewbook/` generates an example MyST notebook with following preamble:
```
---
jupytext:
cell_metadata_filter: -all
formats: md:myst
text_representation:
extension: .md
format_name: myst
format_version: 0.13
jupytext_version: 1.11.5
kernelspec:
display_name: Python 3
language: python
name: python3
---
```
This PR removes the line `cell_metadata_filter: -all`.
It seems extraneous, and causes unexpected behavior, especially for new users of `jupyter-book`, who are likely to use this file as the copy-and-paste basis for all of their MyST markdown notebooks. If they do so, they will find that when they use `jupytext` to sync between MyST and other representations of the notebook (e.g. ipynb for WYSIWYG editing), all cell metadata, including tags, are …
> MAINT: Remove `cell_metadata_filter: -all` from template

- docs/intro.md
- tests/test_build.py
This is a quick fix to get a test passing - it looks like there's an extra file that got added that we didn't update a test for. Here's the list that is created, it all seems reasonable to me so I'm gonna merge this quickly if tests pass so that tests on `main` can be happy.
```
my_book/markdown.md
my_book/references.bib
my_book/_config.yml
my_book/notebooks.ipynb
my_book/content.md
my_book/markdown-notebooks.md
my_book/_toc.yml
my_book/logo.png
my_book/intro.md
```
> Fix test for cookiecutter

- jupyter_book/default_config.yml
- tests/test_config/test_config_sphinx_command.txt
- tests/test_config/test_config_sphinx_command_only_build_toc_files.txt
- tests/test_config/test_get_final_config_custom_myst_extensions.yml
- tests/test_config/test_get_final_config_empty_.yml
- tests/test_config/test_get_final_config_exclude_patterns_.yml
- tests/test_config/test_get_final_config_execute_method_.yml
- tests/test_config/test_get_final_config_extended_syntax_.yml
- tests/test_config/test_get_final_config_html_extra_footer_.yml
- tests/test_config/test_get_final_config_latex_doc_.yml
- tests/test_config/test_get_final_config_repository_.yml
- tests/test_config/test_get_final_config_title_.yml
- tests/test_config/test_mathjax_config_warning.sphinx4.yml
- tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx4.yml
Fixes https://github.com/executablebooks/jupyter-book/issues/1463
See https://github.com/executablebooks/jupyter-book/issues/1463#issuecomment-1445131176
I guess this change should be documented somewhere. But where?
> Change default for launch_buttons.binderhub_url to "" (thus no launch buttons)

- CHANGELOG.md
This PR sets up for release of `v0.14.0`
> RELEASE: v0.14.0

- CHANGELOG.md
- docs/content/content-blocks.md
- jupyter_book/__init__.py
This PR updates to `jupyter-book==0.15`
> RELEASE: v0.15.0

- docs/intro.md
I found two broken links in the intro:
I changed the feature vote link (
https://executablebooks.org/en/latest/feature-vote.html -> https://executablebooks.org/en/latest/feature-vote/
Not sure about the contribute link
contribute/intro.md -> ? 
with this I land on https://jupyterbook.org/en/latest/contribute/intro.md which fails. I should land on https://jupyterbook.org/en/latest/contribute/intro.html I guess but no sure how to edit the source code here though.
> DOCS: fix intro broken links

- docs/publish/gh-pages.md
I looked for an example for this, and didn't find it. Turns out to work without much fiddling! https://github.com/scientificcomputing/mpi-tutorial/pull/31
I'm not sure if there's another place to mention this, e.g. in [execution#cache](https://jupyterbook.org/en/stable/content/execute.html#caching-the-notebook-execution)?
I don't know if there are any issues with caching this way. It seems like one might want jupyter-cache entries to expire individually, but I don't think they do?
> [DOC] persist execution cache on github actions

- .github/workflows/tests.yml
- tox.ini
This should close https://github.com/executablebooks/jupyter-book/issues/1504
Things I wonder about:
- why isn't tox utilized in the CI config?
- should also try adding python 3.11, I'll do that once 3.10 is all good to go.
> CI: adding python 3.10 to the testing matrix and tox

- jupyter_book/default_config.yml
- tests/test_config/test_config_sphinx_command.txt
- tests/test_config/test_config_sphinx_command_only_build_toc_files.txt
- tests/test_config/test_get_final_config_custom_myst_extensions.yml
- tests/test_config/test_get_final_config_empty_.yml
- tests/test_config/test_get_final_config_exclude_patterns_.yml
- tests/test_config/test_get_final_config_execute_method_.yml
- tests/test_config/test_get_final_config_extended_syntax_.yml
- tests/test_config/test_get_final_config_html_extra_footer_.yml
- tests/test_config/test_get_final_config_latex_doc_.yml
- tests/test_config/test_get_final_config_launch_buttons_.yml
- tests/test_config/test_get_final_config_repository_.yml
- tests/test_config/test_get_final_config_sphinx_default_.yml
- tests/test_config/test_get_final_config_sphinx_recurse_.yml
- tests/test_config/test_get_final_config_title_.yml
- tests/test_config/test_mathjax_config_warning.sphinx4.yml
- tests/test_config/test_mathjax_config_warning.sphinx5.yml
- tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx4.yml
- tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx5.yml
Pretty straightforward PR I hope. Big fan of the project all.
I noticed that copyrights seem to be set to 2022 across the whole EB project, but this should update the docs and tests to reference 2023.
> Update copyright year to 2023

- docs/advanced/developers.md
The link for using MyST `eval_rst` directive is out-of-date on master. This PR updates it.
> Update MyST `eval_rst` directive guide link

- docs/publish/gh-pages.md
As the "main" is the default name, it should also trigger the CI. "master" will still work as well.
> Trigger deploy-book action on both master and main

- docs/_config.yml
Clarify that the HTML restructuring occurred in release 0.13.
Link to the changelog entry,
to give users a clue what to look out for.
(Unfortunately, we have to hardcode the full URL:
the documentation for announcements
doesn't say anything about base URLs.)
> [DOC] _config.yml: clarify CSS-breakage announcement

- .pre-commit-config.yaml
- docs/advanced/pdf.md
- docs/content/code-outputs.md
- docs/content/content-blocks.md
- docs/content/executable/output-insert.md
- docs/content/figures.md
- docs/contribute/intro.md
- docs/explain/migration.md
- docs/file-types/notebooks.ipynb
- docs/publish/netlify.md
- docs/start/build.md
- docs/start/create.md
- jupyter_book/config.py
- jupyter_book/sphinx.py
A few minor typo fixes (spelling) and some punctuation improvements/recommendations.
> Typo fixes and formatting for migration.md

- jupyter_book/config.py
See https://github.com/executablebooks/sphinx-book-theme/pull/770
> FIX: Remove sphinx-book-theme from extensions

- docs/_config.yml
Jupyter Book is being rebuilt upon MyST-MD rather than Sphinx. Our [blog post](https://executablebooks.org/en/latest/blog/2024-05-20-jupyter-book-myst/) introduces this, and we'll eventually start putting into place documentation and other scaffolding to make this more visible. For now, just add a banner:
> DOCS: add note about MyST-MD

- README.md
This PR updates the README to point to our blog post, as requested in https://github.com/jupyter-book/jupyter-book/pull/2196#discussion_r1734745739.
> DOCS: update readme to point to blog post

- docs/content/content-blocks.md
based on the glue it's pulling from `output-insert.md` but was linking to `code-outputs.md`
> fix incorrect link

- .github/workflows/deploy.yml
Drop `BASE_URL` in CI now that we're deploying to `http://next.jupyterbook.org`
> ⚙️ Drop `BASE_URL` in GitHub Pages

- .github/workflows/publish.yml
This PR scopes our release workflow to only apply to v1 releases.
> MAINT: only use v1 job for v1 releases

- docs/_config.yml
The PDF build is failing because Sphinx now pulls in `fontawesome5` by default. Although `sphinx-design` should be updated, for now we just patch this in our config.
> DOCS: fall-back to `fontawesome` in LaTeX (and format _config)

- docs/intro.md
The Turing Way now has a non-netlify domain name, which should be stable longterm.
https://github.com/the-turing-way/the-turing-way/issues/3266
> update Turing way URL

- py/jupyter_book/__main__.py
- pyproject.toml
Previously, the Jupyter Book binary used `argv[0]` to determine the binary name. However, we want to promote a specific name: `jupyter book`, which uses the `jupyter` launcher.
> ✏️ Hardcode binary name

- .github/workflows/check-release.yml
- .github/workflows/enforce-label.yml
- .github/workflows/full-release.yml
- .github/workflows/prep-release.yml
- .github/workflows/publish-changelog.yml
- .github/workflows/publish-release.yml
- CHANGELOG.md
This PR follows https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo_from_repo.html to install Jupyter Releaser. The process has become a little more complicated than the last time that I did this, due to the use of a GitHub App, but I think it just needs some better docs.
> 🤖 Add jupyter releaser

- README.md
- docs/about/history.md
- docs/upgrade.md
This replaces executablebooks mentions with jupyter-book mentions
> ✏️ Remove references to executablebooks

- .github/workflows/ci.yml
This just ensures that we can get to the CLI. For now, we rely on upstream testing of the CLI surface.
> 📝 Add simple CI testing of CLI version

- docs/myst.yml
- docs/plugins/dependencies.md
- docs/tutorial/plugins.md
- Adds a howto for plugin dependencies
- Adds the debug howto to the toc
- Fixes a typo in the tutorial
- Moves plugin howtos under a `Plugins` section since they're starting to get numerous!
> Add howto for plugin dependencies

- docs/plugins/directives-and-roles.md
Role plugins do not yet receive a `ctx` argument. This PR replaces use of `ctx` with the native `'myst'` body type.
> 🐝 Fix reference to `ctx` for role plugins

- docs/author/authorship.md
- docs/author/roles-and-directives.md
- docs/myst.yml
- docs/plugins/directives-and-roles.md
- docs/src/admonition.mjs
This adds a few extra pieces of content to our documentation based on some recent questions from people:
1. Add super basic "how to" instructions for directives and roles
2. Show how to add classes to directives
3. Show how to create a custom admonition with a plugin (we can update this in the future if there's a better way)
4. Show an example of adding authorship information metadata
5. A little rearranging for folder names
> ✏️ Add authoring and admonition instructions

- README.md
There's no path from this repo to Jupyter Book 2.x, as far as I can tell. This tries to provide some guidance.
> Add discussion of Jupyter Book 2, along with directions to documentation for 2.x.

- docs/_config.yml
Rename default branch from master to main in `docs/_config_yaml`.
This should resolve the 404 error one gets when clicking on "Suggest edit" on any page of the book.
Resolves issues (probably not a complete list):
- resolves #2242
- resolves #2235 
This is my first pull request. Let me know if some things are not to standard.
Best Johannes
> Rename branch from 'master' to 'main' in _config.yaml

- docs/_config.yml
This updates our banner to use a GitHub issue for ongoing information on the 2.0 switch (instead of using a blog post). My reasoning is that we can use that issue as the "source of truth" for external people that want to learn more about this transition, what to expect, where to learn more, etc. This might change over time so better to use a github issue than a blog post.
Here's the issue:
- https://github.com/jupyter-book/jupyter-book/issues/2281
Any objections from the @jupyter-book/core-team about this? I'm open to alternative suggestions!
> Update banner to use github issue

- .github/ISSUE_TEMPLATE/01_bug.yml
- .github/ISSUE_TEMPLATE/config.yml
This adds a link to the Jupyter Book discussion forum for "new issue" templates.
I also propose that we update our "bug report" issue to just be a general bug report, not something "specific" to Jupyter Book 2. However we should make clear in the issue template that users should specify if this relates to JB 1 or 2.
This way, the new issue button menu should look like this:
1. Open a bug report
2. Open a blank issue
3. Ask a question (links to forum)
4. Request an enhancement (links to forum)
Over time, if people are still opening unhelpful blank issues and not using the forum, then we can consider removing that option so only maintainers can open blank issues.
> Update new issues template to point to discussions forum

- .github/ISSUE_TEMPLATE/01_bug.yml
We accidentally deleted the description field, which isn't allowed
> Add description back to bug report template

- pyproject.toml
The PyPI dependencies block in pyproject.toml
https://github.com/jupyter-book/jupyter-book/blob/a4adf9f618180e92ab7b07d11ca08db6d5cfc04b/pyproject.toml#L48-L53
is too strict, causing installations to fail for locking solves with environments that also specify these.
> 🪢 Loosen PyPI dependencies for nodeenv etc.

- .readthedocs.yaml
I wanted to see how the RTD integration was going, and realized that our builds are failing because `pushd` isn't on the build system, so this is a quick PR to get that working:
> Convert readthedocs pushd to cd

- .readthedocs.yaml
This uses the same build customization pattern recommended by RTD:
https://blog.readthedocs.com/build-customization/
> cd within same command as build for RTD

- py/jupyter_book/__main__.py
- ts/index.ts
This change ensures that the binary on npmjs reports itself to be Jupyter Book!
> 🏷️ Set whitelabelling on NPM package rather than Python

- docs/myst.yml
The workaround detailed in #2256 does not actually work properly — `include`s are evaluated before execution.
We really just need to fix execution. For now, I'm removing this guide from the ToC.
cc @choldgraf
> 📝 Drop reference to execution workaround, as it does not work

- docs/publish/gh-pages.md
This PR updates the legacy docs to reflect the newest GitHub Actions versions.
> DOCS: update gh-pages guidance

- package-lock.json
This PR bumps the `myst-cli` version in our lockfile, so that it is updated for packaging.
> 🔼 Bump `myst-cli` version for release

- .github/ISSUE_TEMPLATE/01_bug.yml
Very minor fix - macOS is spelt macOS, instead of Mac OS.
> Fix macOS spelling in issue template

- docs/start.md
Hello 😊 
Small PR to fix the links for the grid cards on the `Get Started` docs page
> Fix links on docs `Get Started` page

- docs/index.md
- docs/myst.yml
I had some trouble finding the upgrading documentation from JB1, so I made 2 changes here:
1. Add a tab on the index page with the Quickstart to include upgrading instructions
2. Move the upgrading page (back?) the to top level of the TOC
My guess is that this will be one of the most viewed pages on the docs for a good while, so keeping the page highly visible would IMO be a net benefit. Thanks for the great project!
> Add extra links to the upgrading docs page

- docs/index.md
The docs were recently updated to fix the install instructions. An annoying nuance is that `2.0.0` is `>` `2.0.0b0`, so `pip install --pre jupyter-book>=2.0.0` does not succeed.
Closes #2388
> ✍️ Fix install command

- ts/index.ts
This should ensure that `--gh-pages` generates the proper invocation. Fixes #2387
> 🏷️ Set new NPM_ binary name variable
