_data/navigation.yml
_guide/01_overview.md
_guide/07_advanced.md

factoring out relevant files into an "advanced" section so it doesn't scare people off

adding advanced section

---

scripts/generate_summary_from_folders.py

Consistent with __main__ which does already do this defaulting

Made textbook_folder an optional input

---

.gitignore
_build/01/3/Plotting_the_Classics.md
_build/03/1/Expressions.md
_build/03/2/Names.md
_build/03/3/Calls.md
_build/03/4/Introduction_to_Tables.md
_build/04/1/Numbers.md
_build/04/2/Strings.md
_build/04/3/Comparison.md
_build/04/Types.md
_build/features/notebooks.md
scripts/generate_book.py

fixing interact link paths

---

README.md

Line 21 contains the exact same link etc as the one I removed below. This PR is a suggestion on what to do about that.

Delete duplicated link in readme

---

README.md
_includes/interact-update.html

this lets people define alternate locations for their internet links by specifying `?hub=myhuburl.org`

fixing the internet js to not use jquery

---

scripts/generate_book.py
scripts/tests/test_build.py

I don't know if this matters much, but seems like a typo that could cause some confusion if unfixed.

Typo - does it matter?

---

README.md
_sass/components/_components.textbook__sidebar-right.scss
assets/js/scripts.js

This adds a bit of javascript that highlights the current location in the right menu bar!

highlighting to right menu bar

---

_config.yml
_sass/components/_components.textbook__sidebar-right.scss
_sass/inuitcss/generic/_generic.shared.scss

This updates the right sidebar CSS to be a bit more minimal, which should get rid of some of the awkward overlap w/ the right scrollbar that people have reported

updating sidebar css to be more minimal

---

content/features/interact.ipynb

Not much else to add...this may be smallest PR I've ever opened 😀

Fix very small typo

---

_includes/js/thebelab.html
scripts/generate_book.py
scripts/tests/test_build.py

set kernelOptions for thebelab based on notebook's metadata

---

content/guide/06_faq.md

From #93.
I wasn't sure if only the original ("content/") *.md file is needed prior to a PR, or if you prefer `make book` also be run so that the "_build/" file is generated and also included. I checked your wiki for any contribution guidelines but there were none.

Update FAQ with guidelines for Plotly

---

jupyter_book/book_template/_includes/js/thebelab.html
jupyter_book/book_template/assets/js/scripts.js

I believe that this fixes the shortcuts behavior w/ thebelab

fixing thebelab keyboard shortcuts behavior

---

README.md

@choldgraf you might want to enable [codecov](https://codecov.io/) and then this should just work

Add badge for coverage

---

MAINTAINING.md
jupyter_book/book_template/_build/03/1/Expressions.md
jupyter_book/book_template/_build/guide/03_build.md
jupyter_book/book_template/_build/guide/04_faq.md
jupyter_book/book_template/_build/guide/05_advanced.md

updating the build information for the docs because the site is broken, and adding a short explanation of how the docs are deployed.

Build update

---

.circleci/config.yml
jupyter_book/book_template/_includes/js/thebelab.html

This fixes a typo in the thebelab config and also tries to fix the circle builds

fixing thebelab and circle build

---

jupyter_book/book_template/_config.yml

binder links to gh-pages now

---

.circleci/config.yml

think this will work @jasmainak ?

codecov activation

---

jupyter_book/book_template/_includes/js/copy-button.html
jupyter_book/book_template/_sass/components/_components.hidecells.scss

gets the highlighting working properly

hide cells updates

---

jupyter_book/book_template/_sass/components/_components.textbook__page.scss

Otherwise you'll occasionally get things like this :)
With patch it looks like this.

wrap code even if it has no language

---

jupyter_book/book_template/Makefile

fix doc mismatch for "make build"

---

jupyter_book/book_template/content/features/notebooks.ipynb

As 'discussed' here: https://github.com/jupyter/jupyter-book/issues/224

Change text in Markdown cell to correct URL.

---

README.md
jupyter_book/book_template/assets/custom/custom.css
jupyter_book/book_template/content/guide/05_advanced.md
jupyter_book/book_template/content/intro.md
jupyter_book/commands/build.py
jupyter_book/commands/create.py
jupyter_book/commands/upgrade.py
jupyter_book/create.py
jupyter_book/tests/site/requirements.txt
jupyter_book/tests/test_create.py
jupyter_book/toc.py
jupyter_book/utils.py
requirements.txt

This fixes up a bunch of stuff in the issues that have been bugging folks. It clears out most of the cache before v0.5.1
closes #240 
closes #146 	
closes #140 
closes #132 
closes #130 
closes #49

Release fixes

---

jupyter_book/build.py
jupyter_book/commands/__init__.py
jupyter_book/commands/build.py
jupyter_book/main.py

This does some refactoring so that there's a separate "build_page" function, and exposes that function in the CLI. However it's not a very useful function yet, but everything should behave the same way in the meantime.

adding simple page building

---

setup.py

fixes setup.py so our pypi page shows the description

fixing pypi description

---

jupyter_book/book_template/_includes/head.html
jupyter_book/book_template/content/features/limits.md
jupyter_book/book_template/content/features/notebooks.ipynb

This fixes a few broken links that were found with https://www.deadlinkchecker.com/website-dead-link-checker.asp
closes #259

fixing links

---

jupyter_book/create.py
jupyter_book/tests/site/_bibliography/references.bib
jupyter_book/tests/test_create.py

[FIX] Fix references being deleted with jupyter-upgrade

---

jupyter_book/build.py
jupyter_book/commands/build.py
jupyter_book/page.py

This factors out the single-page building code into a separate module to make it easier to grok and potentially to one day build in better one-page support. It should just be cosmetic, nothing big changing here

factoring out page module

---

jupyter_book/book_template/_includes/buttons.html
jupyter_book/book_template/_includes/buttons/download.html

This should make the download PDF button appear on all pages so it works w/ PDF as well

making a download PDF button appear on all pages

---

jupyter_book/book_template/_includes/js/mathjax.html
jupyter_book/book_template/_includes/js/print.html
jupyter_book/book_template/content/features/markdown.md
jupyter_book/book_template/content/guide/04_faq.md

This makes some small improvements to the print functionality, and also standardizes the MathJax configuration to exactly what the notebook uses.
Math rendering on print is still not great, we need to figure out a way to improve that

fixing up print functionality

---

jupyter_book/book_template/_sass/components/_components.textbook.scss
jupyter_book/book_template/_sass/components/_components.textbook__page.scss

This fixes the footer width so it's correct when the page width goes yo 70%

footer width

---

jupyter_book/book_template/content/guide/05_advanced.md

adds a few help entries per a recent set of questions from stats 88

adding help entries

---

.gitignore
jupyter_book/book_template/Makefile
jupyter_book/book_template/_includes/buttons.html

Before, setting page.interact_link = false would result in a missing `</div>` tag which caused lots of problems for page layout.
This PR ensures that the `</div>` always appears.
Without the fix:
With the fix:

Fix missing </div> if page.interact_link is false

---

jupyter_book/book_template/_sass/components/_components.page__nav.scss
jupyter_book/book_template/_sass/components/_components.textbook.scss

Fixes the footer width so it's centered

fixing footer width

---

jupyter_book/book_template/content/features/notebooks.ipynb
jupyter_book/commands/run.py
jupyter_book/main.py
jupyter_book/run.py
jupyter_book/tests/test_run.py

This documents functionality around executing notebooks. @psychemedia wanna give it a whirl after I merge?

documenting execution functionality

---

jupyter_book/book_template/content/guide/04_faq.md

this updates an outdated FAQ entry about escape characters

removing outdated FAQ entry

---

jupyter_book/book_template/_sass/components/_components.textbook__page.scss
jupyter_book/book_template/assets/js/scripts.js

This fixes scroll highlighting so that it's consistent across markdown and notebook-based pages

fixing scrolling

---

jupyter_book/build.py
jupyter_book/commands/build.py
jupyter_book/page.py

Addresses https://github.com/jupyter/jupyter-book/issues/203

[WIP] Add option to clear outputs in build command

---

jupyter_book/create.py

The CLI call was throwing an error - this fixes things

fixing TOC auto gen bug

---

jupyter_book/toc.py

this makes sure the auto-generated TOC is in order

making toc gen sorted

---

jupyter_book/tests/site/content/tests/markdown.md
jupyter_book/tests/test_page.py
jupyter_book/utils.py

fixes the check for yaml metadata to make sure it's actually read in properly

fixing load ntbk function

---

jupyter_book/book_template/_sass/components/_components.thebelab.scss

css for thebelab z-order

---

CHANGELOG.md
RELEASES.md
jupyter_book/book_template/_config.yml

bumping to a new version and adding a changelog

version bump

---

jupyter_book/book_template/_data/toc.yml
jupyter_book/book_template/content/features/beta.md
jupyter_book/book_template/content/features/page.md
jupyter_book/book_template/content/guide/01-5_tour.md
jupyter_book/book_template/content/guide/01_overview.md
jupyter_book/book_template/content/guide/02_create.md
jupyter_book/book_template/content/guide/03_build.md
jupyter_book/book_template/content/guide/04_publish.md
jupyter_book/book_template/content/guide/05_faq.md
jupyter_book/book_template/content/guide/06_advanced.md
jupyter_book/book_template/content/guide/publish/book-html.md
jupyter_book/book_template/content/guide/publish/github-pages.md
jupyter_book/book_template/content/guide/publish/netlify.md
netlify.toml

This updates the getting started guide - it adds a separate folder on "publishing" (which covers both building book HTML and publishing to online providers like GH-pages and Netlify). It also does a bit of refactoring under the hood.

updating getting started guide

---

.github/ISSUE_TEMPLATE.md

I accidentally committed an issue template directly to master instead of making a PR, so this PR fixes it up a bit and also leaves it open for folks to comment.
@emdupre I'd love to know what you think about this template!

fixing issue template

---

jupyter_book/book_template/content/advanced/circleci.ipynb

As mentioned in #462 , here is my pull request for the documentaiton. I tried to follow all the contributing guidelines, but let me know if there is anything I missed!
Cheers,
Alex

[DOC] changed circleci docs to reflect consistent job name

---

docs/publish/gh-pages.md
docs/publish/netlify.md
docs/start/publish.md
jupyter_book/book_template/_config.yml

Updates some of the online publishing documentation

updating deploy docs

---

docs/intro.md

Slightly improves readability?

Small edits to intro page on docs.

---

docs/intro.md

addresses part of #549 
this removes the parts of the mini example that were unnecessary and corrects the ordering of things

clarifying qe mini example

---

docs/advanced/advanced.md
docs/content/content-blocks.md

Document use of pure html

---

docs/customize/toc.md

minor doc tweak to safe the next person 2 minutes

add html section to tip about navbar_number_sections

---

docs/content-types/index.md
docs/intro.md
jupyter_book/sphinx.py
jupyter_book/yaml.py
tests/pages/extra_page.ipynb
tests/pages/single_page.ipynb
tests/test_build.py

updating docs and fixing single page bug

---

docs/customize/config.md
jupyter_book/default_config.yml

closes https://github.com/executablebooks/jupyter-book/issues/620

clarifying config values

---

docs/publish/gh-pages.md

- New option
- Folded logs and split some groups
- Dependencies update
https://github.com/peaceiris/actions-gh-pages/releases
https://github.com/peaceiris/actions-gh-pages/compare/v3.5.9...v3.6.1

bump peaceiris/actions-gh-pages to v3.6.1

---

.gitignore
setup.py

My local testing environment required these changes to pass the tests. 
This PR adds packages required for `jupyter-book` test suite and adjusts the ignore paths for build files produced by tests.

TST: update testing requirements and adjust ignore

---

jupyter_book/sphinx.py

closes https://github.com/executablebooks/sphinx-book-theme/issues/105

fixing suffix in download files

---

jupyter_book/commands/__init__.py

Adding versions to the CLI 
closes https://github.com/executablebooks/jupyter-book/issues/665

adding versions

---

jupyter_book/toc.py
tests/books/toc/_toc_startwithlist.yml
tests/test_tocdirective/test_toc_startwithlist.html

closes https://github.com/executablebooks/jupyter-book/issues/672

fixing toc bug

---

jupyter_book/yaml.py
setup.py

Fixing some logic around topbar repository buttons
closes #706

fixing topbar repo buttons

---

docs/content/execute.md
docs/interactive/interactive.md
setup.py

closes https://github.com/executablebooks/jupyter-book/issues/605
closes https://github.com/executablebooks/jupyter-book/issues/688

Release prep

---

docs/advanced/advanced.md
docs/interactive/hiding.md

Link documentation for adding cell tags in Jupyter from "Hide or remove content" documentation section

---

jupyter_book/directive/toc.py
tests/test_tocdirective/test_toc_startwithlist.html
tests/test_tocdirective/test_toc_urllink.html
tests/test_tocdirective/test_toc_withheaders.html

@phaustin I think this should solve the #738 issue, of having absolute links. 
Let me know if this works fine.
fixes #738

[BUG] Using relative instead of absolute links

---

docs/publish/gh-pages.md

I find this to be useful and want to spread knowledge about it in a sensible way. I'm not sure what makes the most sense but here is one example.
It will make this example more complicated though, so I'm not 100% if I like it.
The GitHub actions documentation about this is available at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

GitHub actions example: note about selective build

---

docs/advanced/advanced.md
docs/advanced/pdf.md
docs/content-types/index.md
docs/customize/toc.md
docs/interactive/hiding.md
jupyter_book/__init__.py
jupyter_book/directive/toc.py
jupyter_book/sphinx.py
setup.py

a prototype to get tableofcontents-style functionality by re-using the Sphinx doctree elements.
cc @AakashGfude - wanna try taking this over and seeing if it'll work?

first pass toc directive

---

docs/advanced/advanced.md

The instruction on activating google analytics is wrong or outdated. By poking around the repo I found the correct way (for JB 0.7.1).

📖 DOCS: Fix google analytics instructions

---

docs/advanced/advanced.md

📚 DOC: note about licenses

---

docs/content/execute.md
docs/customize/toc.md
jupyter_book/toc.py
tests/books/toc/_toc_numbered.yml
tests/test_tocdirective.py
tests/test_tocdirective/test_toc_numbered.html

Adds tests for numbered sections

👌 IMPROVE: improving numbered sections

---

docs/_config.yml
docs/advanced/pdf.md
docs/contribute/develop.md
docs/customize/toc.md
docs/requirements.txt

This adds some more information about `_toc.yml` structure maps on to book structure

📚 DOCS: adding information about page structure

---

docs/content/citations.md

Closes #838.
Right now I'm only pointing to other available styles, rather than providing an example of each.
I realized it might be a bit overwhelming to show all four possible styles in one place, but I'm happy to add this in if folks think it would be useful !

📚 DOC: document available bib styles

---

docs/customize/toc.md

More discussion of this in issue #844...
This PR assumes it's not possible to nest files in the landing page entry.

📚 DOCS: Adding documentation of `home_page_in_navbar`

---

docs/_config.yml
docs/contribute/intro.md
docs/intro.md
jupyter_book/sphinx.py

Adds some documentation about feature voting and also updates the front page with a feature list that's a bit easier to read per @chrisjsewell 's suggestion.

📚 DOC: improving front-page + feature voting

---

docs/intro.md

Because currently you are drowning the page in blue 😉

📚 DOCS: Reduce length of link text

---

docs/start/build.md

This looks okay?
cc: @chrisjsewell @mmcky

🔧 MAINTAIN: Update docs to reflect output dir of page

---

docs/content/citations.md

change "if you with" to "if you wish"

🔧 MAINTAIN: fix minor typo

---

docs/content/content-blocks.md

I think this section accidentally got bumped underneath a different section

🔧 MAINTAIN: Moving admonition section

---

docs/intro.md

This gives a shot at using definition lists for the participation links, let's see how it looks...

🔧 MAINTAIN: Reworking participation links

---

docs/interactive/comments/utterances.md

The utteranc.es app must also be given permissions to read/write to the repository issues

📚 DOCS: Update utterances.md

---

.gitignore
jupyter_book/commands/__init__.py

Closes https://github.com/executablebooks/jupyter-book/issues/1050 
This seems to work (it runs and does check links...) but I have no clue how to add a test to avoid future regressions.

🐛 FIX: Restore linkcheck to builder opts

---

docs/content/citations.md
docs/content/content-blocks.md

This updates the sections on citations / references, as well as on panels, to include more complete information with more examples and configuration.

📚 DOCS: Improving citations and panels

---

docs/_config.yml
docs/intro.md

Adds a link to the Jupyter Book gallery and updates some of the text in that box

📚 DOCS: adding link to gallery

---

docs/content/figures.md

The example was not the same as the code, which is confusing especially for the `:align: center` option!
Note: I haven't tested this locally - so not sure if the alignment actually works?!

📚 DOCS: Update figures markdown for the example

---

docs/advanced/advanced.md

Trivial edit to delete stray `)`.

🔧 MAINTAIN: Remove stray parenthesis

---

docs/content/content-blocks.md

📚 DOCS: Fix typo

---

CHANGELOG.md
docs/content/content-blocks.md

As per review of #1189, just some minor things
See https://deploy-preview-1199--jupyter-book.netlify.app/reference/_changelog.html

📚 DOCS: Update CHANGELOG.md

---

docs/content/myst.md

This PR adds a simple warning admonition for `multiline role` limitations
https://github.com/executablebooks/MyST-Parser/issues/269

📚 DOCS: add warning for roles and multiple line bug

---

docs/content/content-blocks.md

closes https://github.com/executablebooks/jupyter-book/issues/1259

DOC: Update content-blocks.md

---

docs/advanced/sphinx.md

📚 DOC: fix indent in YAML

---

docs/content/content-blocks.md

closes https://github.com/executablebooks/jupyter-book/issues/1257

📚 DOCS: Minor typo in docs

---

docs/publish/gh-pages.md

I am updating the documentation based on reported on #1265

📚 DOCS: Clarifying the github pages publishing guide

---

docs/customize/toc.md

📚 DOCS: Explain use of `title:` for url entry

---

docs/content/citations.md
docs/tutorials/references.md

📚 DOCS: Clarify where to put the ref style in _config

---

setup.cfg
tests/test_tocdirective/test_toc_latex_parts.tex
tests/test_tocdirective/test_toc_latex_urllink.tex

This PR upgrades `sphinx-jupyterbook-latex==0.4.2` which includes [the following improvements](https://github.com/executablebooks/sphinx-jupyterbook-latex/blob/master/CHANGELOG.md#042---2021-07-09)

⬆️ UPGRADE: Upgrade to sphinx-jupyterbook-latex==0.4.2

---

CHANGELOG.md
jupyter_book/__init__.py

Setup PR for release of `jupyter-book==0.11.2`

🚀 RELEASE: Preparation for jupyter-book==0.11.2

---

docs/publish/gh-pages.md

📚 DOCS: Clarify Version Note for Github Actions DOCS

---

docs/file-types/myst-notebooks.md

Very minor change to fix link syntax

📚 DOCS: Fix syntax for MyST-NB link

---

setup.cfg
tests/test_build/_toc_numbered.html
tests/test_build/_toc_numbered_depth.html
tests/test_build/_toc_numbered_depth_parts_subset.html
tests/test_build/_toc_numbered_parts.html
tests/test_build/_toc_numbered_parts_subset.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_multitoc_numbering_false.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_parts_subset_multitoc_numbering_false.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_multitoc_numbering_false.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_multitoc_numbering_false.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_subset_multitoc_numbering_false.html
tests/test_tocdirective/test_toc_parts_sidebar.html

This PR updates to `sphinx-thebe~=0.0.10`
https://sphinx-thebe.readthedocs.io/en/latest/changelog.html#v0-0-10-2021-08-24

⬆️ UPGRADE:  sphinx-thebe to v0.0.10 and sphinx-book-theme to v0.1.3

---

docs/cite.md

closes https://github.com/executablebooks/jupyter-book/issues/1454

📚` DOCS: Fix cite link

---

docs/publish/readthedocs.md

See https://read-the-docs-guidelines.readthedocs-hosted.com/branding.html#brand-name.

Update Read the Docs brand name

---

docs/start/create.md

Fix small typo in jupyter book template

DOCS: Fix minor typo

---

docs/start/publish.md

Suggested edit to make it more clear what will happen if .nojekyll or the flag is not added. 
Totally optional suggestion, I wont be offended if you close this pr without a merge!
https://github.com/executablebooks/meta/discussions/583

DOCS: Update publish.md to include 404 warning

---

docs/intro.md

closes https://github.com/executablebooks/jupyter-book/issues/1583

DOC: Fix mis-spelling

---

docs/reference/cheatsheet.md

DOCS: Update rendered table to be same as the md

---

docs/content/content-blocks.md

Short section on how to add index terms to a Jupyter Book.

DOCS: Add section on indexes

---

CHANGELOG.md
jupyter_book/__init__.py

This is a minor release that brings in a few new versions of packages, but no major new functionality.

RELEASE: v0.12.2

---

tests/test_config/test_config_sphinx_command.txt
tests/test_config/test_config_sphinx_command_only_build_toc_files.txt
tests/test_config/test_get_final_config_custom_myst_extensions.yml
tests/test_config/test_get_final_config_empty_.yml
tests/test_config/test_get_final_config_exclude_patterns_.yml
tests/test_config/test_get_final_config_execute_method_.yml
tests/test_config/test_get_final_config_extended_syntax_.yml
tests/test_config/test_get_final_config_html_extra_footer_.yml
tests/test_config/test_get_final_config_latex_doc_.yml
tests/test_config/test_get_final_config_launch_buttons_.yml
tests/test_config/test_get_final_config_repository_.yml
tests/test_config/test_get_final_config_sphinx_default_.yml
tests/test_config/test_get_final_config_sphinx_recurse_.yml
tests/test_config/test_get_final_config_title_.yml
tests/test_config/test_mathjax_config_warning.sphinx3.yml
tests/test_config/test_mathjax_config_warning.sphinx4.yml
tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx3.yml
tests/test_config/test_mathjax_config_warning_mathjax2path.sphinx4.yml

MAINT: Copyright bug in regression tests

---

CHANGELOG.md
jupyter_book/__init__.py

This PR sets up for the minor release of `0.13.1`

[Release] Prepare for v0.13.1

---

docs/reference/cheatsheet.md

Closes https://github.com/executablebooks/jupyter-book/issues/1668

DOCS: Change syntax highlighting example

---

docs/content/executable/output-insert.md

FIX: Address typo in docs

---

docs/advanced/pdf.md

Corrects link to features page in sphinx-jupyterbook-latex

DOCS: Fix broken link in pdf.md

---

docs/start/new-file.md

Providing the answer to this ticket: https://github.com/executablebooks/jupyter-book/issues/1493

DOCS: Clarify toc update tip

---

docs/advanced/html.md

As commented in #1345, it's the pull request for the correction of the raised points

DOCS: Improve custom admonitions documentation

---

docs/_toc.yml

fixes https://github.com/executablebooks/jupyter-book/issues/1931
Thanks @nickledave !

DOCS: Fix gallery URL

---

docs/intro.md

📖 Update JupyterBook gallery link

---

CHANGELOG.md

Minor PR to fix some formatting

DOCS: Fix table and formatting in CHANGELOG

---

pyproject.toml
tests/test_build/_toc_numbered.sphinx4.html
tests/test_build/_toc_numbered.sphinx5.html
tests/test_build/_toc_numbered_depth.sphinx4.html
tests/test_build/_toc_numbered_depth.sphinx5.html
tests/test_build/_toc_numbered_depth_parts_subset.sphinx4.html
tests/test_build/_toc_numbered_depth_parts_subset.sphinx5.html
tests/test_build/_toc_numbered_parts.sphinx4.html
tests/test_build/_toc_numbered_parts.sphinx5.html
tests/test_build/_toc_numbered_parts_subset.sphinx4.html
tests/test_build/_toc_numbered_parts_subset.sphinx5.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_multitoc_numbering_false.sphinx4.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_multitoc_numbering_false.sphinx5.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_parts_subset_multitoc_numbering_false.sphinx4.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_parts_subset_multitoc_numbering_false.sphinx5.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_multitoc_numbering_false.sphinx4.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_multitoc_numbering_false.sphinx5.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_multitoc_numbering_false.sphinx4.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_multitoc_numbering_false.sphinx5.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_subset_multitoc_numbering_false.sphinx4.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_subset_multitoc_numbering_false.sphinx5.html
tests/test_tocdirective/test_toc_parts_sidebar.sphinx4.html
tests/test_tocdirective/test_toc_parts_sidebar.sphinx5.html

It would be great to be able to use sphinx-book-theme 1.0.0!
See https://github.com/executablebooks/jupyter-book/pull/1842#issuecomment-1450053056

Update requirement sphinx-book-theme to ~=1.0.0

---

docs/interactive/interactive.ipynb

Address https://github.com/executablebooks/jupyter-book/issues/1950

DOCS: Add documentation about suppressing warnings for showing plotly figures

---

docs/start/example-book.md
docs/start/new-file.md

This minor PR contains two simple commits that fix #2071.

[FIX, DOC]; fixes #2071

---

.github/workflows/tests.yml
pyproject.toml
tests/test_build/_toc_numbered.sphinx7.html
tests/test_build/_toc_numbered_depth.sphinx7.html
tests/test_build/_toc_numbered_depth_parts_subset.sphinx7.html
tests/test_build/_toc_numbered_parts.sphinx7.html
tests/test_build/_toc_numbered_parts_subset.sphinx7.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_multitoc_numbering_false.sphinx7.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_depth_parts_subset_multitoc_numbering_false.sphinx7.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_multitoc_numbering_false.sphinx7.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_multitoc_numbering_false.sphinx7.html
tests/test_sphinx_multitoc_numbering/_toc_numbered_parts_subset_multitoc_numbering_false.sphinx7.html
tests/test_tocdirective/test_toc_parts_sidebar.sphinx7.html

Codecov uploads are broken right now, and don't seem to behave with OIDC. To avoid this bottlenecking much-needed releases, I'm temporarily disabling this.

MAINT: disable codecov uploader

---

jupyter_book/config_schema.json

This fixes a missing field in our schema

FIX: schema for bibfiles

---

.binder/requirements.txt
docs/content/executable/output-insert.md
pyproject.toml

DOCS: fix glue of NumPy variables

---

jupyter_book/config.py

FIX: pull in config for plausible

---

jupyter_book/default_config.yml

This PR updates the default configuration used by Jupyter Book.

FIX: update default config

---

README.md

Make a note about the project being in maintenance mode.

DOCS: update readme with note about maintenance

---

flake.lock
flake.nix

This PR adds a Nix Flake for creating the development environment used to build and contribute to Jupyter Book 2.

❄️ Add Nix devshell flake

---

README.md

This PR is tiny, and just changes some prose/links in our readme.

📔 Simplify readme

---

CHANGELOG.md

The changelog had been neglected recently :shaking_face:

MAINT: update changelog

---

docs/myst.yml

This PR pulls in common Jupyter Book documentation configuration to `myst.yml`

🖇️ Use shared config in docs

---

docs/plugins/directives.mjs

🐜 Fix reference to deleted directives

---

docs/plugins/directives.mjs

Link to https://github.com/jupyter-book/mystmd/issues/1101

🌍 Add documentation about plugin origin

---

.github/workflows/check-release.yml
.github/workflows/enforce-label.yml
.github/workflows/full-release.yml
.github/workflows/prep-release.yml
.github/workflows/publish-changelog.yml
.github/workflows/publish-release.yml

It will be easier to use `workflow_dispatch` from `main`.

🤖 Backport #2257 (Add Jupyter releaser)

---

.github/workflows/deploy.yml
docs/execute/generate-myst.md
docs/myst.yml
docs/start.md
docs/tutorial/execution.md

This adds a little demo showing how you can programmatically execute code. I wasn't sure where to put it, so I just added it to the execution tutorial. Would it be better as a standalone "execution" collection of how-tos instead?
- closes https://github.com/jupyter-book/mystmd/issues/1638

📕 Show how you can programmatically include content

---

package.json

This PR pulls in a number of `myst-cli` improvements:
https://github.com/jupyter-book/mystmd/compare/mystmd@1.3.18...mystmd@1.3.23

⬆️ Bump `myst-cli` version

---

.github/workflows/pdf.yml
.github/workflows/tests.yml
jupyter_book/pdf.py

I missed that the previous PR broke our tests altogether! This PR fixes that, and ensures that they pass.

fix: use 'main' for branch name

---

docs/content/execute.md

noticed missing backtick, fixed a few typos, too.

DOC: minor fixes

---

docs/index.md

🛠️ Fix install instructions for JB2

---

ts/index.ts

This updates our init routine so that the proper package is installed!

🎬 Improve whitelabelling for `jupyter book init`

---

package-lock.json
package.json

Update to the latest MyST CLI version.

🐫 Bump MyST CLI version

---

package-lock.json
package.json

🔼 Bump `myst-cli` to 1.6.0 for release

---

pyproject.toml

Remove duplicated `beautifulsoup4`

Updated pyproject.toml

---

docs/site.yml

🐛 Update discord link
